// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: components/properties/v1/action.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Components_Properties_V1_ActionType: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case navigation // = 0
  case apiCall // = 1
  case UNRECOGNIZED(Int)

  public init() {
    self = .navigation
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .navigation
    case 1: self = .apiCall
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .navigation: return 0
    case .apiCall: return 1
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Components_Properties_V1_ActionType] = [
    .navigation,
    .apiCall,
  ]

}

public struct Components_Properties_V1_Action: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var actionType: Components_Properties_V1_ActionType = .navigation

  public var actionValue: String = String()

  public var destination: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "components.properties.v1"

extension Components_Properties_V1_ActionType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0NAVIGATION\0\u{1}API_CALL\0")
}

extension Components_Properties_V1_Action: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Action"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}action_type\0\u{3}action_value\0\u{1}destination\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.actionType) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.actionValue) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.destination) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.actionType != .navigation {
      try visitor.visitSingularEnumField(value: self.actionType, fieldNumber: 1)
    }
    if !self.actionValue.isEmpty {
      try visitor.visitSingularStringField(value: self.actionValue, fieldNumber: 2)
    }
    if !self.destination.isEmpty {
      try visitor.visitSingularStringField(value: self.destination, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Components_Properties_V1_Action, rhs: Components_Properties_V1_Action) -> Bool {
    if lhs.actionType != rhs.actionType {return false}
    if lhs.actionValue != rhs.actionValue {return false}
    if lhs.destination != rhs.destination {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
