// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/icon/v1/icon.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.cg.sdui.components.icon.v1;

