// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/icon/v1/icon.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.cg.sdui.components.icon.v1;

@kotlin.jvm.JvmName("-initializeicon")
public inline fun icon(block: com.cg.sdui.components.icon.v1.IconKt.Dsl.() -> kotlin.Unit): com.cg.sdui.components.icon.v1.Icon =
  com.cg.sdui.components.icon.v1.IconKt.Dsl._create(com.cg.sdui.components.icon.v1.Icon.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `components.icon.v1.Icon`
 */
public object IconKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.cg.sdui.components.icon.v1.Icon.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.cg.sdui.components.icon.v1.Icon.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.cg.sdui.components.icon.v1.Icon = _builder.build()

    /**
     * `int32 size = 1 [json_name = "size"];`
     */
    public var size: kotlin.Int
      @kotlin.jvm.JvmName("getSize")
        get() = _builder.size
      @kotlin.jvm.JvmName("setSize")
        set(value) {
        _builder.size = value
      }
    /**
     * `int32 size = 1 [json_name = "size"];`
     */
    public fun clearSize() {
      _builder.clearSize()
    }

    /**
     * `string tint = 2 [json_name = "tint"];`
     */
    public var tint: kotlin.String
      @kotlin.jvm.JvmName("getTint")
        get() = _builder.tint
      @kotlin.jvm.JvmName("setTint")
        set(value) {
        _builder.tint = value
      }
    /**
     * `string tint = 2 [json_name = "tint"];`
     */
    public fun clearTint() {
      _builder.clearTint()
    }

    /**
     * `string src = 3 [json_name = "src"];`
     */
    public var src: kotlin.String
      @kotlin.jvm.JvmName("getSrc")
        get() = _builder.src
      @kotlin.jvm.JvmName("setSrc")
        set(value) {
        _builder.src = value
      }
    /**
     * `string src = 3 [json_name = "src"];`
     */
    public fun clearSrc() {
      _builder.clearSrc()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.cg.sdui.components.icon.v1.Icon.copy(block: `com.cg.sdui.components.icon.v1`.IconKt.Dsl.() -> kotlin.Unit): com.cg.sdui.components.icon.v1.Icon =
  `com.cg.sdui.components.icon.v1`.IconKt.Dsl._create(this.toBuilder()).apply { block() }._build()

