// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/column/column.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.components.list;

/**
 * Protobuf type {@code components.list.SDUIColumn}
 */
public final class SDUIColumn extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:components.list.SDUIColumn)
    SDUIColumnOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      SDUIColumn.class.getName());
  }
  // Use SDUIColumn.newBuilder() to construct.
  private SDUIColumn(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SDUIColumn() {
    sduiComponent_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cg.sdui.components.list.ColumnProto.internal_static_components_list_SDUIColumn_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cg.sdui.components.list.ColumnProto.internal_static_components_list_SDUIColumn_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cg.sdui.components.list.SDUIColumn.class, com.cg.sdui.components.list.SDUIColumn.Builder.class);
  }

  public static final int SDUI_COMPONENT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.cg.sdui.components.properties.v1.SDUIComponent> sduiComponent_;
  /**
   * <code>repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];</code>
   */
  @java.lang.Override
  public java.util.List<com.cg.sdui.components.properties.v1.SDUIComponent> getSduiComponentList() {
    return sduiComponent_;
  }
  /**
   * <code>repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.cg.sdui.components.properties.v1.SDUIComponentOrBuilder> 
      getSduiComponentOrBuilderList() {
    return sduiComponent_;
  }
  /**
   * <code>repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];</code>
   */
  @java.lang.Override
  public int getSduiComponentCount() {
    return sduiComponent_.size();
  }
  /**
   * <code>repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];</code>
   */
  @java.lang.Override
  public com.cg.sdui.components.properties.v1.SDUIComponent getSduiComponent(int index) {
    return sduiComponent_.get(index);
  }
  /**
   * <code>repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];</code>
   */
  @java.lang.Override
  public com.cg.sdui.components.properties.v1.SDUIComponentOrBuilder getSduiComponentOrBuilder(
      int index) {
    return sduiComponent_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < sduiComponent_.size(); i++) {
      output.writeMessage(1, sduiComponent_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < sduiComponent_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, sduiComponent_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cg.sdui.components.list.SDUIColumn)) {
      return super.equals(obj);
    }
    com.cg.sdui.components.list.SDUIColumn other = (com.cg.sdui.components.list.SDUIColumn) obj;

    if (!getSduiComponentList()
        .equals(other.getSduiComponentList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSduiComponentCount() > 0) {
      hash = (37 * hash) + SDUI_COMPONENT_FIELD_NUMBER;
      hash = (53 * hash) + getSduiComponentList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cg.sdui.components.list.SDUIColumn parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.sdui.components.list.SDUIColumn parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.sdui.components.list.SDUIColumn parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.sdui.components.list.SDUIColumn parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.sdui.components.list.SDUIColumn parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.sdui.components.list.SDUIColumn parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.sdui.components.list.SDUIColumn parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cg.sdui.components.list.SDUIColumn parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.cg.sdui.components.list.SDUIColumn parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.cg.sdui.components.list.SDUIColumn parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cg.sdui.components.list.SDUIColumn parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cg.sdui.components.list.SDUIColumn parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cg.sdui.components.list.SDUIColumn prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code components.list.SDUIColumn}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:components.list.SDUIColumn)
      com.cg.sdui.components.list.SDUIColumnOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cg.sdui.components.list.ColumnProto.internal_static_components_list_SDUIColumn_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cg.sdui.components.list.ColumnProto.internal_static_components_list_SDUIColumn_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cg.sdui.components.list.SDUIColumn.class, com.cg.sdui.components.list.SDUIColumn.Builder.class);
    }

    // Construct using com.cg.sdui.components.list.SDUIColumn.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (sduiComponentBuilder_ == null) {
        sduiComponent_ = java.util.Collections.emptyList();
      } else {
        sduiComponent_ = null;
        sduiComponentBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cg.sdui.components.list.ColumnProto.internal_static_components_list_SDUIColumn_descriptor;
    }

    @java.lang.Override
    public com.cg.sdui.components.list.SDUIColumn getDefaultInstanceForType() {
      return com.cg.sdui.components.list.SDUIColumn.getDefaultInstance();
    }

    @java.lang.Override
    public com.cg.sdui.components.list.SDUIColumn build() {
      com.cg.sdui.components.list.SDUIColumn result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cg.sdui.components.list.SDUIColumn buildPartial() {
      com.cg.sdui.components.list.SDUIColumn result = new com.cg.sdui.components.list.SDUIColumn(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.cg.sdui.components.list.SDUIColumn result) {
      if (sduiComponentBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          sduiComponent_ = java.util.Collections.unmodifiableList(sduiComponent_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.sduiComponent_ = sduiComponent_;
      } else {
        result.sduiComponent_ = sduiComponentBuilder_.build();
      }
    }

    private void buildPartial0(com.cg.sdui.components.list.SDUIColumn result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cg.sdui.components.list.SDUIColumn) {
        return mergeFrom((com.cg.sdui.components.list.SDUIColumn)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cg.sdui.components.list.SDUIColumn other) {
      if (other == com.cg.sdui.components.list.SDUIColumn.getDefaultInstance()) return this;
      if (sduiComponentBuilder_ == null) {
        if (!other.sduiComponent_.isEmpty()) {
          if (sduiComponent_.isEmpty()) {
            sduiComponent_ = other.sduiComponent_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSduiComponentIsMutable();
            sduiComponent_.addAll(other.sduiComponent_);
          }
          onChanged();
        }
      } else {
        if (!other.sduiComponent_.isEmpty()) {
          if (sduiComponentBuilder_.isEmpty()) {
            sduiComponentBuilder_.dispose();
            sduiComponentBuilder_ = null;
            sduiComponent_ = other.sduiComponent_;
            bitField0_ = (bitField0_ & ~0x00000001);
            sduiComponentBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getSduiComponentFieldBuilder() : null;
          } else {
            sduiComponentBuilder_.addAllMessages(other.sduiComponent_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.cg.sdui.components.properties.v1.SDUIComponent m =
                  input.readMessage(
                      com.cg.sdui.components.properties.v1.SDUIComponent.parser(),
                      extensionRegistry);
              if (sduiComponentBuilder_ == null) {
                ensureSduiComponentIsMutable();
                sduiComponent_.add(m);
              } else {
                sduiComponentBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.cg.sdui.components.properties.v1.SDUIComponent> sduiComponent_ =
      java.util.Collections.emptyList();
    private void ensureSduiComponentIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        sduiComponent_ = new java.util.ArrayList<com.cg.sdui.components.properties.v1.SDUIComponent>(sduiComponent_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.cg.sdui.components.properties.v1.SDUIComponent, com.cg.sdui.components.properties.v1.SDUIComponent.Builder, com.cg.sdui.components.properties.v1.SDUIComponentOrBuilder> sduiComponentBuilder_;

    /**
     * <code>repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];</code>
     */
    public java.util.List<com.cg.sdui.components.properties.v1.SDUIComponent> getSduiComponentList() {
      if (sduiComponentBuilder_ == null) {
        return java.util.Collections.unmodifiableList(sduiComponent_);
      } else {
        return sduiComponentBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];</code>
     */
    public int getSduiComponentCount() {
      if (sduiComponentBuilder_ == null) {
        return sduiComponent_.size();
      } else {
        return sduiComponentBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];</code>
     */
    public com.cg.sdui.components.properties.v1.SDUIComponent getSduiComponent(int index) {
      if (sduiComponentBuilder_ == null) {
        return sduiComponent_.get(index);
      } else {
        return sduiComponentBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];</code>
     */
    public Builder setSduiComponent(
        int index, com.cg.sdui.components.properties.v1.SDUIComponent value) {
      if (sduiComponentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSduiComponentIsMutable();
        sduiComponent_.set(index, value);
        onChanged();
      } else {
        sduiComponentBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];</code>
     */
    public Builder setSduiComponent(
        int index, com.cg.sdui.components.properties.v1.SDUIComponent.Builder builderForValue) {
      if (sduiComponentBuilder_ == null) {
        ensureSduiComponentIsMutable();
        sduiComponent_.set(index, builderForValue.build());
        onChanged();
      } else {
        sduiComponentBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];</code>
     */
    public Builder addSduiComponent(com.cg.sdui.components.properties.v1.SDUIComponent value) {
      if (sduiComponentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSduiComponentIsMutable();
        sduiComponent_.add(value);
        onChanged();
      } else {
        sduiComponentBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];</code>
     */
    public Builder addSduiComponent(
        int index, com.cg.sdui.components.properties.v1.SDUIComponent value) {
      if (sduiComponentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSduiComponentIsMutable();
        sduiComponent_.add(index, value);
        onChanged();
      } else {
        sduiComponentBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];</code>
     */
    public Builder addSduiComponent(
        com.cg.sdui.components.properties.v1.SDUIComponent.Builder builderForValue) {
      if (sduiComponentBuilder_ == null) {
        ensureSduiComponentIsMutable();
        sduiComponent_.add(builderForValue.build());
        onChanged();
      } else {
        sduiComponentBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];</code>
     */
    public Builder addSduiComponent(
        int index, com.cg.sdui.components.properties.v1.SDUIComponent.Builder builderForValue) {
      if (sduiComponentBuilder_ == null) {
        ensureSduiComponentIsMutable();
        sduiComponent_.add(index, builderForValue.build());
        onChanged();
      } else {
        sduiComponentBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];</code>
     */
    public Builder addAllSduiComponent(
        java.lang.Iterable<? extends com.cg.sdui.components.properties.v1.SDUIComponent> values) {
      if (sduiComponentBuilder_ == null) {
        ensureSduiComponentIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, sduiComponent_);
        onChanged();
      } else {
        sduiComponentBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];</code>
     */
    public Builder clearSduiComponent() {
      if (sduiComponentBuilder_ == null) {
        sduiComponent_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        sduiComponentBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];</code>
     */
    public Builder removeSduiComponent(int index) {
      if (sduiComponentBuilder_ == null) {
        ensureSduiComponentIsMutable();
        sduiComponent_.remove(index);
        onChanged();
      } else {
        sduiComponentBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];</code>
     */
    public com.cg.sdui.components.properties.v1.SDUIComponent.Builder getSduiComponentBuilder(
        int index) {
      return getSduiComponentFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];</code>
     */
    public com.cg.sdui.components.properties.v1.SDUIComponentOrBuilder getSduiComponentOrBuilder(
        int index) {
      if (sduiComponentBuilder_ == null) {
        return sduiComponent_.get(index);  } else {
        return sduiComponentBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];</code>
     */
    public java.util.List<? extends com.cg.sdui.components.properties.v1.SDUIComponentOrBuilder> 
         getSduiComponentOrBuilderList() {
      if (sduiComponentBuilder_ != null) {
        return sduiComponentBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(sduiComponent_);
      }
    }
    /**
     * <code>repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];</code>
     */
    public com.cg.sdui.components.properties.v1.SDUIComponent.Builder addSduiComponentBuilder() {
      return getSduiComponentFieldBuilder().addBuilder(
          com.cg.sdui.components.properties.v1.SDUIComponent.getDefaultInstance());
    }
    /**
     * <code>repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];</code>
     */
    public com.cg.sdui.components.properties.v1.SDUIComponent.Builder addSduiComponentBuilder(
        int index) {
      return getSduiComponentFieldBuilder().addBuilder(
          index, com.cg.sdui.components.properties.v1.SDUIComponent.getDefaultInstance());
    }
    /**
     * <code>repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];</code>
     */
    public java.util.List<com.cg.sdui.components.properties.v1.SDUIComponent.Builder> 
         getSduiComponentBuilderList() {
      return getSduiComponentFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.cg.sdui.components.properties.v1.SDUIComponent, com.cg.sdui.components.properties.v1.SDUIComponent.Builder, com.cg.sdui.components.properties.v1.SDUIComponentOrBuilder> 
        getSduiComponentFieldBuilder() {
      if (sduiComponentBuilder_ == null) {
        sduiComponentBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.cg.sdui.components.properties.v1.SDUIComponent, com.cg.sdui.components.properties.v1.SDUIComponent.Builder, com.cg.sdui.components.properties.v1.SDUIComponentOrBuilder>(
                sduiComponent_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        sduiComponent_ = null;
      }
      return sduiComponentBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:components.list.SDUIColumn)
  }

  // @@protoc_insertion_point(class_scope:components.list.SDUIColumn)
  private static final com.cg.sdui.components.list.SDUIColumn DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cg.sdui.components.list.SDUIColumn();
  }

  public static com.cg.sdui.components.list.SDUIColumn getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SDUIColumn>
      PARSER = new com.google.protobuf.AbstractParser<SDUIColumn>() {
    @java.lang.Override
    public SDUIColumn parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SDUIColumn> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SDUIColumn> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cg.sdui.components.list.SDUIColumn getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

