// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/text/v1/text.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.components.text.v1;

/**
 * Protobuf enum {@code components.text.v1.AndroidTypography}
 */
public enum AndroidTypography
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>displayLarge = 0;</code>
   */
  displayLarge(0),
  /**
   * <code>displayMedium = 1;</code>
   */
  displayMedium(1),
  /**
   * <code>displaySmall = 2;</code>
   */
  displaySmall(2),
  /**
   * <code>headlineLarge = 3;</code>
   */
  headlineLarge(3),
  /**
   * <code>headlineMedium = 4;</code>
   */
  headlineMedium(4),
  /**
   * <code>headlineSmall = 5;</code>
   */
  headlineSmall(5),
  /**
   * <code>titleLarge = 6;</code>
   */
  titleLarge(6),
  /**
   * <code>titleMedium = 7;</code>
   */
  titleMedium(7),
  /**
   * <code>titleSmall = 8;</code>
   */
  titleSmall(8),
  /**
   * <code>bodyLarge = 9;</code>
   */
  bodyLarge(9),
  /**
   * <code>bodyMedium = 10;</code>
   */
  bodyMedium(10),
  /**
   * <code>bodySmall = 11;</code>
   */
  bodySmall(11),
  /**
   * <code>labelLarge = 12;</code>
   */
  labelLarge(12),
  /**
   * <code>labelMedium = 13;</code>
   */
  labelMedium(13),
  /**
   * <code>labelSmall = 14;</code>
   */
  labelSmall(14),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      AndroidTypography.class.getName());
  }
  /**
   * <code>displayLarge = 0;</code>
   */
  public static final int displayLarge_VALUE = 0;
  /**
   * <code>displayMedium = 1;</code>
   */
  public static final int displayMedium_VALUE = 1;
  /**
   * <code>displaySmall = 2;</code>
   */
  public static final int displaySmall_VALUE = 2;
  /**
   * <code>headlineLarge = 3;</code>
   */
  public static final int headlineLarge_VALUE = 3;
  /**
   * <code>headlineMedium = 4;</code>
   */
  public static final int headlineMedium_VALUE = 4;
  /**
   * <code>headlineSmall = 5;</code>
   */
  public static final int headlineSmall_VALUE = 5;
  /**
   * <code>titleLarge = 6;</code>
   */
  public static final int titleLarge_VALUE = 6;
  /**
   * <code>titleMedium = 7;</code>
   */
  public static final int titleMedium_VALUE = 7;
  /**
   * <code>titleSmall = 8;</code>
   */
  public static final int titleSmall_VALUE = 8;
  /**
   * <code>bodyLarge = 9;</code>
   */
  public static final int bodyLarge_VALUE = 9;
  /**
   * <code>bodyMedium = 10;</code>
   */
  public static final int bodyMedium_VALUE = 10;
  /**
   * <code>bodySmall = 11;</code>
   */
  public static final int bodySmall_VALUE = 11;
  /**
   * <code>labelLarge = 12;</code>
   */
  public static final int labelLarge_VALUE = 12;
  /**
   * <code>labelMedium = 13;</code>
   */
  public static final int labelMedium_VALUE = 13;
  /**
   * <code>labelSmall = 14;</code>
   */
  public static final int labelSmall_VALUE = 14;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static AndroidTypography valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static AndroidTypography forNumber(int value) {
    switch (value) {
      case 0: return displayLarge;
      case 1: return displayMedium;
      case 2: return displaySmall;
      case 3: return headlineLarge;
      case 4: return headlineMedium;
      case 5: return headlineSmall;
      case 6: return titleLarge;
      case 7: return titleMedium;
      case 8: return titleSmall;
      case 9: return bodyLarge;
      case 10: return bodyMedium;
      case 11: return bodySmall;
      case 12: return labelLarge;
      case 13: return labelMedium;
      case 14: return labelSmall;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<AndroidTypography>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      AndroidTypography> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<AndroidTypography>() {
          public AndroidTypography findValueByNumber(int number) {
            return AndroidTypography.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.cg.sdui.components.text.v1.TextProto.getDescriptor().getEnumTypes().get(1);
  }

  private static final AndroidTypography[] VALUES = values();

  public static AndroidTypography valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private AndroidTypography(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:components.text.v1.AndroidTypography)
}

