// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/text/v1/text.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.components.text.v1;

/**
 * Protobuf enum {@code components.text.v1.IOSTypography}
 */
public enum IOSTypography
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>largeTitle = 0;</code>
   */
  largeTitle(0),
  /**
   * <code>title_1 = 1;</code>
   */
  title_1(1),
  /**
   * <code>title_2 = 2;</code>
   */
  title_2(2),
  /**
   * <code>title_3 = 3;</code>
   */
  title_3(3),
  /**
   * <code>headline = 4;</code>
   */
  headline(4),
  /**
   * <code>body = 5;</code>
   */
  body(5),
  /**
   * <code>callout = 6;</code>
   */
  callout(6),
  /**
   * <code>subhead = 7;</code>
   */
  subhead(7),
  /**
   * <code>footnote = 8;</code>
   */
  footnote(8),
  /**
   * <code>caption_1 = 9;</code>
   */
  caption_1(9),
  /**
   * <code>caption_2 = 10;</code>
   */
  caption_2(10),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      IOSTypography.class.getName());
  }
  /**
   * <code>largeTitle = 0;</code>
   */
  public static final int largeTitle_VALUE = 0;
  /**
   * <code>title_1 = 1;</code>
   */
  public static final int title_1_VALUE = 1;
  /**
   * <code>title_2 = 2;</code>
   */
  public static final int title_2_VALUE = 2;
  /**
   * <code>title_3 = 3;</code>
   */
  public static final int title_3_VALUE = 3;
  /**
   * <code>headline = 4;</code>
   */
  public static final int headline_VALUE = 4;
  /**
   * <code>body = 5;</code>
   */
  public static final int body_VALUE = 5;
  /**
   * <code>callout = 6;</code>
   */
  public static final int callout_VALUE = 6;
  /**
   * <code>subhead = 7;</code>
   */
  public static final int subhead_VALUE = 7;
  /**
   * <code>footnote = 8;</code>
   */
  public static final int footnote_VALUE = 8;
  /**
   * <code>caption_1 = 9;</code>
   */
  public static final int caption_1_VALUE = 9;
  /**
   * <code>caption_2 = 10;</code>
   */
  public static final int caption_2_VALUE = 10;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static IOSTypography valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static IOSTypography forNumber(int value) {
    switch (value) {
      case 0: return largeTitle;
      case 1: return title_1;
      case 2: return title_2;
      case 3: return title_3;
      case 4: return headline;
      case 5: return body;
      case 6: return callout;
      case 7: return subhead;
      case 8: return footnote;
      case 9: return caption_1;
      case 10: return caption_2;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<IOSTypography>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      IOSTypography> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<IOSTypography>() {
          public IOSTypography findValueByNumber(int number) {
            return IOSTypography.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.cg.sdui.components.text.v1.TextProto.getDescriptor().getEnumTypes().get(2);
  }

  private static final IOSTypography[] VALUES = values();

  public static IOSTypography valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private IOSTypography(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:components.text.v1.IOSTypography)
}

