// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/text/v1/text.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.components.text.v1;

public interface SDUITextViewOrBuilder extends
    // @@protoc_insertion_point(interface_extends:components.text.v1.SDUITextView)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string text = 1 [json_name = "text"];</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 1 [json_name = "text"];</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>bool enabled = 2 [json_name = "enabled"];</code>
   * @return The enabled.
   */
  boolean getEnabled();

  /**
   * <code>.components.properties.v1.Action action = 3 [json_name = "action"];</code>
   * @return Whether the action field is set.
   */
  boolean hasAction();
  /**
   * <code>.components.properties.v1.Action action = 3 [json_name = "action"];</code>
   * @return The action.
   */
  com.cg.sdui.components.properties.v1.Action getAction();
  /**
   * <code>.components.properties.v1.Action action = 3 [json_name = "action"];</code>
   */
  com.cg.sdui.components.properties.v1.ActionOrBuilder getActionOrBuilder();

  /**
   * <code>.components.text.v1.TextStyle style = 4 [json_name = "style"];</code>
   * @return Whether the style field is set.
   */
  boolean hasStyle();
  /**
   * <code>.components.text.v1.TextStyle style = 4 [json_name = "style"];</code>
   * @return The style.
   */
  com.cg.sdui.components.text.v1.TextStyle getStyle();
  /**
   * <code>.components.text.v1.TextStyle style = 4 [json_name = "style"];</code>
   */
  com.cg.sdui.components.text.v1.TextStyleOrBuilder getStyleOrBuilder();
}
