// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/text/v1/text.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.components.text.v1;

/**
 * Protobuf type {@code components.text.v1.SDUITextView}
 */
public final class SDUITextView extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:components.text.v1.SDUITextView)
    SDUITextViewOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      SDUITextView.class.getName());
  }
  // Use SDUITextView.newBuilder() to construct.
  private SDUITextView(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SDUITextView() {
    text_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cg.sdui.components.text.v1.TextProto.internal_static_components_text_v1_SDUITextView_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cg.sdui.components.text.v1.TextProto.internal_static_components_text_v1_SDUITextView_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cg.sdui.components.text.v1.SDUITextView.class, com.cg.sdui.components.text.v1.SDUITextView.Builder.class);
  }

  private int bitField0_;
  public static final int TEXT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object text_ = "";
  /**
   * <code>string text = 1 [json_name = "text"];</code>
   * @return The text.
   */
  @java.lang.Override
  public java.lang.String getText() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      text_ = s;
      return s;
    }
  }
  /**
   * <code>string text = 1 [json_name = "text"];</code>
   * @return The bytes for text.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTextBytes() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      text_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENABLED_FIELD_NUMBER = 2;
  private boolean enabled_ = false;
  /**
   * <code>bool enabled = 2 [json_name = "enabled"];</code>
   * @return The enabled.
   */
  @java.lang.Override
  public boolean getEnabled() {
    return enabled_;
  }

  public static final int ACTION_FIELD_NUMBER = 3;
  private com.cg.sdui.components.properties.v1.Action action_;
  /**
   * <code>.components.properties.v1.Action action = 3 [json_name = "action"];</code>
   * @return Whether the action field is set.
   */
  @java.lang.Override
  public boolean hasAction() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.components.properties.v1.Action action = 3 [json_name = "action"];</code>
   * @return The action.
   */
  @java.lang.Override
  public com.cg.sdui.components.properties.v1.Action getAction() {
    return action_ == null ? com.cg.sdui.components.properties.v1.Action.getDefaultInstance() : action_;
  }
  /**
   * <code>.components.properties.v1.Action action = 3 [json_name = "action"];</code>
   */
  @java.lang.Override
  public com.cg.sdui.components.properties.v1.ActionOrBuilder getActionOrBuilder() {
    return action_ == null ? com.cg.sdui.components.properties.v1.Action.getDefaultInstance() : action_;
  }

  public static final int STYLE_FIELD_NUMBER = 4;
  private com.cg.sdui.components.text.v1.TextStyle style_;
  /**
   * <code>.components.text.v1.TextStyle style = 4 [json_name = "style"];</code>
   * @return Whether the style field is set.
   */
  @java.lang.Override
  public boolean hasStyle() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.components.text.v1.TextStyle style = 4 [json_name = "style"];</code>
   * @return The style.
   */
  @java.lang.Override
  public com.cg.sdui.components.text.v1.TextStyle getStyle() {
    return style_ == null ? com.cg.sdui.components.text.v1.TextStyle.getDefaultInstance() : style_;
  }
  /**
   * <code>.components.text.v1.TextStyle style = 4 [json_name = "style"];</code>
   */
  @java.lang.Override
  public com.cg.sdui.components.text.v1.TextStyleOrBuilder getStyleOrBuilder() {
    return style_ == null ? com.cg.sdui.components.text.v1.TextStyle.getDefaultInstance() : style_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, text_);
    }
    if (enabled_ != false) {
      output.writeBool(2, enabled_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(3, getAction());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(4, getStyle());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, text_);
    }
    if (enabled_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, enabled_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getAction());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getStyle());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cg.sdui.components.text.v1.SDUITextView)) {
      return super.equals(obj);
    }
    com.cg.sdui.components.text.v1.SDUITextView other = (com.cg.sdui.components.text.v1.SDUITextView) obj;

    if (!getText()
        .equals(other.getText())) return false;
    if (getEnabled()
        != other.getEnabled()) return false;
    if (hasAction() != other.hasAction()) return false;
    if (hasAction()) {
      if (!getAction()
          .equals(other.getAction())) return false;
    }
    if (hasStyle() != other.hasStyle()) return false;
    if (hasStyle()) {
      if (!getStyle()
          .equals(other.getStyle())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEXT_FIELD_NUMBER;
    hash = (53 * hash) + getText().hashCode();
    hash = (37 * hash) + ENABLED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getEnabled());
    if (hasAction()) {
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction().hashCode();
    }
    if (hasStyle()) {
      hash = (37 * hash) + STYLE_FIELD_NUMBER;
      hash = (53 * hash) + getStyle().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cg.sdui.components.text.v1.SDUITextView parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.sdui.components.text.v1.SDUITextView parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.sdui.components.text.v1.SDUITextView parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.sdui.components.text.v1.SDUITextView parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.sdui.components.text.v1.SDUITextView parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.sdui.components.text.v1.SDUITextView parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.sdui.components.text.v1.SDUITextView parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cg.sdui.components.text.v1.SDUITextView parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.cg.sdui.components.text.v1.SDUITextView parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.cg.sdui.components.text.v1.SDUITextView parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cg.sdui.components.text.v1.SDUITextView parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cg.sdui.components.text.v1.SDUITextView parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cg.sdui.components.text.v1.SDUITextView prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code components.text.v1.SDUITextView}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:components.text.v1.SDUITextView)
      com.cg.sdui.components.text.v1.SDUITextViewOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cg.sdui.components.text.v1.TextProto.internal_static_components_text_v1_SDUITextView_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cg.sdui.components.text.v1.TextProto.internal_static_components_text_v1_SDUITextView_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cg.sdui.components.text.v1.SDUITextView.class, com.cg.sdui.components.text.v1.SDUITextView.Builder.class);
    }

    // Construct using com.cg.sdui.components.text.v1.SDUITextView.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getActionFieldBuilder();
        getStyleFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      text_ = "";
      enabled_ = false;
      action_ = null;
      if (actionBuilder_ != null) {
        actionBuilder_.dispose();
        actionBuilder_ = null;
      }
      style_ = null;
      if (styleBuilder_ != null) {
        styleBuilder_.dispose();
        styleBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cg.sdui.components.text.v1.TextProto.internal_static_components_text_v1_SDUITextView_descriptor;
    }

    @java.lang.Override
    public com.cg.sdui.components.text.v1.SDUITextView getDefaultInstanceForType() {
      return com.cg.sdui.components.text.v1.SDUITextView.getDefaultInstance();
    }

    @java.lang.Override
    public com.cg.sdui.components.text.v1.SDUITextView build() {
      com.cg.sdui.components.text.v1.SDUITextView result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cg.sdui.components.text.v1.SDUITextView buildPartial() {
      com.cg.sdui.components.text.v1.SDUITextView result = new com.cg.sdui.components.text.v1.SDUITextView(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.cg.sdui.components.text.v1.SDUITextView result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.text_ = text_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.enabled_ = enabled_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.action_ = actionBuilder_ == null
            ? action_
            : actionBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.style_ = styleBuilder_ == null
            ? style_
            : styleBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cg.sdui.components.text.v1.SDUITextView) {
        return mergeFrom((com.cg.sdui.components.text.v1.SDUITextView)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cg.sdui.components.text.v1.SDUITextView other) {
      if (other == com.cg.sdui.components.text.v1.SDUITextView.getDefaultInstance()) return this;
      if (!other.getText().isEmpty()) {
        text_ = other.text_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getEnabled() != false) {
        setEnabled(other.getEnabled());
      }
      if (other.hasAction()) {
        mergeAction(other.getAction());
      }
      if (other.hasStyle()) {
        mergeStyle(other.getStyle());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              text_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              enabled_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              input.readMessage(
                  getActionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getStyleFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object text_ = "";
    /**
     * <code>string text = 1 [json_name = "text"];</code>
     * @return The text.
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string text = 1 [json_name = "text"];</code>
     * @return The bytes for text.
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string text = 1 [json_name = "text"];</code>
     * @param value The text to set.
     * @return This builder for chaining.
     */
    public Builder setText(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      text_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string text = 1 [json_name = "text"];</code>
     * @return This builder for chaining.
     */
    public Builder clearText() {
      text_ = getDefaultInstance().getText();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string text = 1 [json_name = "text"];</code>
     * @param value The bytes for text to set.
     * @return This builder for chaining.
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      text_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private boolean enabled_ ;
    /**
     * <code>bool enabled = 2 [json_name = "enabled"];</code>
     * @return The enabled.
     */
    @java.lang.Override
    public boolean getEnabled() {
      return enabled_;
    }
    /**
     * <code>bool enabled = 2 [json_name = "enabled"];</code>
     * @param value The enabled to set.
     * @return This builder for chaining.
     */
    public Builder setEnabled(boolean value) {

      enabled_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool enabled = 2 [json_name = "enabled"];</code>
     * @return This builder for chaining.
     */
    public Builder clearEnabled() {
      bitField0_ = (bitField0_ & ~0x00000002);
      enabled_ = false;
      onChanged();
      return this;
    }

    private com.cg.sdui.components.properties.v1.Action action_;
    private com.google.protobuf.SingleFieldBuilder<
        com.cg.sdui.components.properties.v1.Action, com.cg.sdui.components.properties.v1.Action.Builder, com.cg.sdui.components.properties.v1.ActionOrBuilder> actionBuilder_;
    /**
     * <code>.components.properties.v1.Action action = 3 [json_name = "action"];</code>
     * @return Whether the action field is set.
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.components.properties.v1.Action action = 3 [json_name = "action"];</code>
     * @return The action.
     */
    public com.cg.sdui.components.properties.v1.Action getAction() {
      if (actionBuilder_ == null) {
        return action_ == null ? com.cg.sdui.components.properties.v1.Action.getDefaultInstance() : action_;
      } else {
        return actionBuilder_.getMessage();
      }
    }
    /**
     * <code>.components.properties.v1.Action action = 3 [json_name = "action"];</code>
     */
    public Builder setAction(com.cg.sdui.components.properties.v1.Action value) {
      if (actionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        action_ = value;
      } else {
        actionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.components.properties.v1.Action action = 3 [json_name = "action"];</code>
     */
    public Builder setAction(
        com.cg.sdui.components.properties.v1.Action.Builder builderForValue) {
      if (actionBuilder_ == null) {
        action_ = builderForValue.build();
      } else {
        actionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.components.properties.v1.Action action = 3 [json_name = "action"];</code>
     */
    public Builder mergeAction(com.cg.sdui.components.properties.v1.Action value) {
      if (actionBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          action_ != null &&
          action_ != com.cg.sdui.components.properties.v1.Action.getDefaultInstance()) {
          getActionBuilder().mergeFrom(value);
        } else {
          action_ = value;
        }
      } else {
        actionBuilder_.mergeFrom(value);
      }
      if (action_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.components.properties.v1.Action action = 3 [json_name = "action"];</code>
     */
    public Builder clearAction() {
      bitField0_ = (bitField0_ & ~0x00000004);
      action_ = null;
      if (actionBuilder_ != null) {
        actionBuilder_.dispose();
        actionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.components.properties.v1.Action action = 3 [json_name = "action"];</code>
     */
    public com.cg.sdui.components.properties.v1.Action.Builder getActionBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getActionFieldBuilder().getBuilder();
    }
    /**
     * <code>.components.properties.v1.Action action = 3 [json_name = "action"];</code>
     */
    public com.cg.sdui.components.properties.v1.ActionOrBuilder getActionOrBuilder() {
      if (actionBuilder_ != null) {
        return actionBuilder_.getMessageOrBuilder();
      } else {
        return action_ == null ?
            com.cg.sdui.components.properties.v1.Action.getDefaultInstance() : action_;
      }
    }
    /**
     * <code>.components.properties.v1.Action action = 3 [json_name = "action"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.cg.sdui.components.properties.v1.Action, com.cg.sdui.components.properties.v1.Action.Builder, com.cg.sdui.components.properties.v1.ActionOrBuilder> 
        getActionFieldBuilder() {
      if (actionBuilder_ == null) {
        actionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.cg.sdui.components.properties.v1.Action, com.cg.sdui.components.properties.v1.Action.Builder, com.cg.sdui.components.properties.v1.ActionOrBuilder>(
                getAction(),
                getParentForChildren(),
                isClean());
        action_ = null;
      }
      return actionBuilder_;
    }

    private com.cg.sdui.components.text.v1.TextStyle style_;
    private com.google.protobuf.SingleFieldBuilder<
        com.cg.sdui.components.text.v1.TextStyle, com.cg.sdui.components.text.v1.TextStyle.Builder, com.cg.sdui.components.text.v1.TextStyleOrBuilder> styleBuilder_;
    /**
     * <code>.components.text.v1.TextStyle style = 4 [json_name = "style"];</code>
     * @return Whether the style field is set.
     */
    public boolean hasStyle() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.components.text.v1.TextStyle style = 4 [json_name = "style"];</code>
     * @return The style.
     */
    public com.cg.sdui.components.text.v1.TextStyle getStyle() {
      if (styleBuilder_ == null) {
        return style_ == null ? com.cg.sdui.components.text.v1.TextStyle.getDefaultInstance() : style_;
      } else {
        return styleBuilder_.getMessage();
      }
    }
    /**
     * <code>.components.text.v1.TextStyle style = 4 [json_name = "style"];</code>
     */
    public Builder setStyle(com.cg.sdui.components.text.v1.TextStyle value) {
      if (styleBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        style_ = value;
      } else {
        styleBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.components.text.v1.TextStyle style = 4 [json_name = "style"];</code>
     */
    public Builder setStyle(
        com.cg.sdui.components.text.v1.TextStyle.Builder builderForValue) {
      if (styleBuilder_ == null) {
        style_ = builderForValue.build();
      } else {
        styleBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.components.text.v1.TextStyle style = 4 [json_name = "style"];</code>
     */
    public Builder mergeStyle(com.cg.sdui.components.text.v1.TextStyle value) {
      if (styleBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          style_ != null &&
          style_ != com.cg.sdui.components.text.v1.TextStyle.getDefaultInstance()) {
          getStyleBuilder().mergeFrom(value);
        } else {
          style_ = value;
        }
      } else {
        styleBuilder_.mergeFrom(value);
      }
      if (style_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.components.text.v1.TextStyle style = 4 [json_name = "style"];</code>
     */
    public Builder clearStyle() {
      bitField0_ = (bitField0_ & ~0x00000008);
      style_ = null;
      if (styleBuilder_ != null) {
        styleBuilder_.dispose();
        styleBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.components.text.v1.TextStyle style = 4 [json_name = "style"];</code>
     */
    public com.cg.sdui.components.text.v1.TextStyle.Builder getStyleBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getStyleFieldBuilder().getBuilder();
    }
    /**
     * <code>.components.text.v1.TextStyle style = 4 [json_name = "style"];</code>
     */
    public com.cg.sdui.components.text.v1.TextStyleOrBuilder getStyleOrBuilder() {
      if (styleBuilder_ != null) {
        return styleBuilder_.getMessageOrBuilder();
      } else {
        return style_ == null ?
            com.cg.sdui.components.text.v1.TextStyle.getDefaultInstance() : style_;
      }
    }
    /**
     * <code>.components.text.v1.TextStyle style = 4 [json_name = "style"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.cg.sdui.components.text.v1.TextStyle, com.cg.sdui.components.text.v1.TextStyle.Builder, com.cg.sdui.components.text.v1.TextStyleOrBuilder> 
        getStyleFieldBuilder() {
      if (styleBuilder_ == null) {
        styleBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.cg.sdui.components.text.v1.TextStyle, com.cg.sdui.components.text.v1.TextStyle.Builder, com.cg.sdui.components.text.v1.TextStyleOrBuilder>(
                getStyle(),
                getParentForChildren(),
                isClean());
        style_ = null;
      }
      return styleBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:components.text.v1.SDUITextView)
  }

  // @@protoc_insertion_point(class_scope:components.text.v1.SDUITextView)
  private static final com.cg.sdui.components.text.v1.SDUITextView DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cg.sdui.components.text.v1.SDUITextView();
  }

  public static com.cg.sdui.components.text.v1.SDUITextView getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SDUITextView>
      PARSER = new com.google.protobuf.AbstractParser<SDUITextView>() {
    @java.lang.Override
    public SDUITextView parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SDUITextView> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SDUITextView> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cg.sdui.components.text.v1.SDUITextView getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

