// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/text/v1/text.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.components.text.v1;

public interface TextStyleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:components.text.v1.TextStyle)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool fullWidth = 1 [json_name = "fullWidth"];</code>
   * @return The fullWidth.
   */
  boolean getFullWidth();

  /**
   * <code>string backgroundColor = 2 [json_name = "backgroundColor"];</code>
   * @return The backgroundColor.
   */
  java.lang.String getBackgroundColor();
  /**
   * <code>string backgroundColor = 2 [json_name = "backgroundColor"];</code>
   * @return The bytes for backgroundColor.
   */
  com.google.protobuf.ByteString
      getBackgroundColorBytes();

  /**
   * <code>string txtColor = 3 [json_name = "txtColor"];</code>
   * @return The txtColor.
   */
  java.lang.String getTxtColor();
  /**
   * <code>string txtColor = 3 [json_name = "txtColor"];</code>
   * @return The bytes for txtColor.
   */
  com.google.protobuf.ByteString
      getTxtColorBytes();

  /**
   * <code>.components.properties.v1.TextAlignment textAlignment = 4 [json_name = "textAlignment"];</code>
   * @return The enum numeric value on the wire for textAlignment.
   */
  int getTextAlignmentValue();
  /**
   * <code>.components.properties.v1.TextAlignment textAlignment = 4 [json_name = "textAlignment"];</code>
   * @return The textAlignment.
   */
  com.cg.sdui.components.properties.v1.TextAlignment getTextAlignment();

  /**
   * <code>int32 max_lines = 5 [json_name = "maxLines"];</code>
   * @return The maxLines.
   */
  int getMaxLines();

  /**
   * <code>int32 max_lenght = 6 [json_name = "maxLenght"];</code>
   * @return The maxLenght.
   */
  int getMaxLenght();

  /**
   * <code>.components.text.v1.TextOverFlow text_over_flow = 7 [json_name = "textOverFlow"];</code>
   * @return The enum numeric value on the wire for textOverFlow.
   */
  int getTextOverFlowValue();
  /**
   * <code>.components.text.v1.TextOverFlow text_over_flow = 7 [json_name = "textOverFlow"];</code>
   * @return The textOverFlow.
   */
  com.cg.sdui.components.text.v1.TextOverFlow getTextOverFlow();

  /**
   * <code>optional .components.text.v1.AndroidTypography android_typography = 8 [json_name = "androidTypography"];</code>
   * @return Whether the androidTypography field is set.
   */
  boolean hasAndroidTypography();
  /**
   * <code>optional .components.text.v1.AndroidTypography android_typography = 8 [json_name = "androidTypography"];</code>
   * @return The enum numeric value on the wire for androidTypography.
   */
  int getAndroidTypographyValue();
  /**
   * <code>optional .components.text.v1.AndroidTypography android_typography = 8 [json_name = "androidTypography"];</code>
   * @return The androidTypography.
   */
  com.cg.sdui.components.text.v1.AndroidTypography getAndroidTypography();

  /**
   * <code>optional .components.text.v1.IOSTypography ios_typography = 9 [json_name = "iosTypography"];</code>
   * @return Whether the iosTypography field is set.
   */
  boolean hasIosTypography();
  /**
   * <code>optional .components.text.v1.IOSTypography ios_typography = 9 [json_name = "iosTypography"];</code>
   * @return The enum numeric value on the wire for iosTypography.
   */
  int getIosTypographyValue();
  /**
   * <code>optional .components.text.v1.IOSTypography ios_typography = 9 [json_name = "iosTypography"];</code>
   * @return The iosTypography.
   */
  com.cg.sdui.components.text.v1.IOSTypography getIosTypography();
}
