// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/text/v1/text.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.components.text.v1;

/**
 * Protobuf type {@code components.text.v1.TextStyle}
 */
public final class TextStyle extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:components.text.v1.TextStyle)
    TextStyleOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      TextStyle.class.getName());
  }
  // Use TextStyle.newBuilder() to construct.
  private TextStyle(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TextStyle() {
    backgroundColor_ = "";
    txtColor_ = "";
    textAlignment_ = 0;
    textOverFlow_ = 0;
    androidTypography_ = 0;
    iosTypography_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cg.sdui.components.text.v1.TextProto.internal_static_components_text_v1_TextStyle_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cg.sdui.components.text.v1.TextProto.internal_static_components_text_v1_TextStyle_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cg.sdui.components.text.v1.TextStyle.class, com.cg.sdui.components.text.v1.TextStyle.Builder.class);
  }

  private int bitField0_;
  public static final int FULLWIDTH_FIELD_NUMBER = 1;
  private boolean fullWidth_ = false;
  /**
   * <code>bool fullWidth = 1 [json_name = "fullWidth"];</code>
   * @return The fullWidth.
   */
  @java.lang.Override
  public boolean getFullWidth() {
    return fullWidth_;
  }

  public static final int BACKGROUNDCOLOR_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object backgroundColor_ = "";
  /**
   * <code>string backgroundColor = 2 [json_name = "backgroundColor"];</code>
   * @return The backgroundColor.
   */
  @java.lang.Override
  public java.lang.String getBackgroundColor() {
    java.lang.Object ref = backgroundColor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      backgroundColor_ = s;
      return s;
    }
  }
  /**
   * <code>string backgroundColor = 2 [json_name = "backgroundColor"];</code>
   * @return The bytes for backgroundColor.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBackgroundColorBytes() {
    java.lang.Object ref = backgroundColor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      backgroundColor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TXTCOLOR_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object txtColor_ = "";
  /**
   * <code>string txtColor = 3 [json_name = "txtColor"];</code>
   * @return The txtColor.
   */
  @java.lang.Override
  public java.lang.String getTxtColor() {
    java.lang.Object ref = txtColor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      txtColor_ = s;
      return s;
    }
  }
  /**
   * <code>string txtColor = 3 [json_name = "txtColor"];</code>
   * @return The bytes for txtColor.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTxtColorBytes() {
    java.lang.Object ref = txtColor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      txtColor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEXTALIGNMENT_FIELD_NUMBER = 4;
  private int textAlignment_ = 0;
  /**
   * <code>.components.properties.v1.TextAlignment textAlignment = 4 [json_name = "textAlignment"];</code>
   * @return The enum numeric value on the wire for textAlignment.
   */
  @java.lang.Override public int getTextAlignmentValue() {
    return textAlignment_;
  }
  /**
   * <code>.components.properties.v1.TextAlignment textAlignment = 4 [json_name = "textAlignment"];</code>
   * @return The textAlignment.
   */
  @java.lang.Override public com.cg.sdui.components.properties.v1.TextAlignment getTextAlignment() {
    com.cg.sdui.components.properties.v1.TextAlignment result = com.cg.sdui.components.properties.v1.TextAlignment.forNumber(textAlignment_);
    return result == null ? com.cg.sdui.components.properties.v1.TextAlignment.UNRECOGNIZED : result;
  }

  public static final int MAX_LINES_FIELD_NUMBER = 5;
  private int maxLines_ = 0;
  /**
   * <code>int32 max_lines = 5 [json_name = "maxLines"];</code>
   * @return The maxLines.
   */
  @java.lang.Override
  public int getMaxLines() {
    return maxLines_;
  }

  public static final int MAX_LENGHT_FIELD_NUMBER = 6;
  private int maxLenght_ = 0;
  /**
   * <code>int32 max_lenght = 6 [json_name = "maxLenght"];</code>
   * @return The maxLenght.
   */
  @java.lang.Override
  public int getMaxLenght() {
    return maxLenght_;
  }

  public static final int TEXT_OVER_FLOW_FIELD_NUMBER = 7;
  private int textOverFlow_ = 0;
  /**
   * <code>.components.text.v1.TextOverFlow text_over_flow = 7 [json_name = "textOverFlow"];</code>
   * @return The enum numeric value on the wire for textOverFlow.
   */
  @java.lang.Override public int getTextOverFlowValue() {
    return textOverFlow_;
  }
  /**
   * <code>.components.text.v1.TextOverFlow text_over_flow = 7 [json_name = "textOverFlow"];</code>
   * @return The textOverFlow.
   */
  @java.lang.Override public com.cg.sdui.components.text.v1.TextOverFlow getTextOverFlow() {
    com.cg.sdui.components.text.v1.TextOverFlow result = com.cg.sdui.components.text.v1.TextOverFlow.forNumber(textOverFlow_);
    return result == null ? com.cg.sdui.components.text.v1.TextOverFlow.UNRECOGNIZED : result;
  }

  public static final int ANDROID_TYPOGRAPHY_FIELD_NUMBER = 8;
  private int androidTypography_ = 0;
  /**
   * <code>optional .components.text.v1.AndroidTypography android_typography = 8 [json_name = "androidTypography"];</code>
   * @return Whether the androidTypography field is set.
   */
  @java.lang.Override public boolean hasAndroidTypography() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .components.text.v1.AndroidTypography android_typography = 8 [json_name = "androidTypography"];</code>
   * @return The enum numeric value on the wire for androidTypography.
   */
  @java.lang.Override public int getAndroidTypographyValue() {
    return androidTypography_;
  }
  /**
   * <code>optional .components.text.v1.AndroidTypography android_typography = 8 [json_name = "androidTypography"];</code>
   * @return The androidTypography.
   */
  @java.lang.Override public com.cg.sdui.components.text.v1.AndroidTypography getAndroidTypography() {
    com.cg.sdui.components.text.v1.AndroidTypography result = com.cg.sdui.components.text.v1.AndroidTypography.forNumber(androidTypography_);
    return result == null ? com.cg.sdui.components.text.v1.AndroidTypography.UNRECOGNIZED : result;
  }

  public static final int IOS_TYPOGRAPHY_FIELD_NUMBER = 9;
  private int iosTypography_ = 0;
  /**
   * <code>optional .components.text.v1.IOSTypography ios_typography = 9 [json_name = "iosTypography"];</code>
   * @return Whether the iosTypography field is set.
   */
  @java.lang.Override public boolean hasIosTypography() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .components.text.v1.IOSTypography ios_typography = 9 [json_name = "iosTypography"];</code>
   * @return The enum numeric value on the wire for iosTypography.
   */
  @java.lang.Override public int getIosTypographyValue() {
    return iosTypography_;
  }
  /**
   * <code>optional .components.text.v1.IOSTypography ios_typography = 9 [json_name = "iosTypography"];</code>
   * @return The iosTypography.
   */
  @java.lang.Override public com.cg.sdui.components.text.v1.IOSTypography getIosTypography() {
    com.cg.sdui.components.text.v1.IOSTypography result = com.cg.sdui.components.text.v1.IOSTypography.forNumber(iosTypography_);
    return result == null ? com.cg.sdui.components.text.v1.IOSTypography.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (fullWidth_ != false) {
      output.writeBool(1, fullWidth_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(backgroundColor_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, backgroundColor_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(txtColor_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, txtColor_);
    }
    if (textAlignment_ != com.cg.sdui.components.properties.v1.TextAlignment.CENTER.getNumber()) {
      output.writeEnum(4, textAlignment_);
    }
    if (maxLines_ != 0) {
      output.writeInt32(5, maxLines_);
    }
    if (maxLenght_ != 0) {
      output.writeInt32(6, maxLenght_);
    }
    if (textOverFlow_ != com.cg.sdui.components.text.v1.TextOverFlow.WRAP.getNumber()) {
      output.writeEnum(7, textOverFlow_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(8, androidTypography_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeEnum(9, iosTypography_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (fullWidth_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, fullWidth_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(backgroundColor_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, backgroundColor_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(txtColor_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, txtColor_);
    }
    if (textAlignment_ != com.cg.sdui.components.properties.v1.TextAlignment.CENTER.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, textAlignment_);
    }
    if (maxLines_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, maxLines_);
    }
    if (maxLenght_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, maxLenght_);
    }
    if (textOverFlow_ != com.cg.sdui.components.text.v1.TextOverFlow.WRAP.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(7, textOverFlow_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(8, androidTypography_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(9, iosTypography_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cg.sdui.components.text.v1.TextStyle)) {
      return super.equals(obj);
    }
    com.cg.sdui.components.text.v1.TextStyle other = (com.cg.sdui.components.text.v1.TextStyle) obj;

    if (getFullWidth()
        != other.getFullWidth()) return false;
    if (!getBackgroundColor()
        .equals(other.getBackgroundColor())) return false;
    if (!getTxtColor()
        .equals(other.getTxtColor())) return false;
    if (textAlignment_ != other.textAlignment_) return false;
    if (getMaxLines()
        != other.getMaxLines()) return false;
    if (getMaxLenght()
        != other.getMaxLenght()) return false;
    if (textOverFlow_ != other.textOverFlow_) return false;
    if (hasAndroidTypography() != other.hasAndroidTypography()) return false;
    if (hasAndroidTypography()) {
      if (androidTypography_ != other.androidTypography_) return false;
    }
    if (hasIosTypography() != other.hasIosTypography()) return false;
    if (hasIosTypography()) {
      if (iosTypography_ != other.iosTypography_) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FULLWIDTH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getFullWidth());
    hash = (37 * hash) + BACKGROUNDCOLOR_FIELD_NUMBER;
    hash = (53 * hash) + getBackgroundColor().hashCode();
    hash = (37 * hash) + TXTCOLOR_FIELD_NUMBER;
    hash = (53 * hash) + getTxtColor().hashCode();
    hash = (37 * hash) + TEXTALIGNMENT_FIELD_NUMBER;
    hash = (53 * hash) + textAlignment_;
    hash = (37 * hash) + MAX_LINES_FIELD_NUMBER;
    hash = (53 * hash) + getMaxLines();
    hash = (37 * hash) + MAX_LENGHT_FIELD_NUMBER;
    hash = (53 * hash) + getMaxLenght();
    hash = (37 * hash) + TEXT_OVER_FLOW_FIELD_NUMBER;
    hash = (53 * hash) + textOverFlow_;
    if (hasAndroidTypography()) {
      hash = (37 * hash) + ANDROID_TYPOGRAPHY_FIELD_NUMBER;
      hash = (53 * hash) + androidTypography_;
    }
    if (hasIosTypography()) {
      hash = (37 * hash) + IOS_TYPOGRAPHY_FIELD_NUMBER;
      hash = (53 * hash) + iosTypography_;
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cg.sdui.components.text.v1.TextStyle parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.sdui.components.text.v1.TextStyle parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.sdui.components.text.v1.TextStyle parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.sdui.components.text.v1.TextStyle parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.sdui.components.text.v1.TextStyle parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.sdui.components.text.v1.TextStyle parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.sdui.components.text.v1.TextStyle parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cg.sdui.components.text.v1.TextStyle parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.cg.sdui.components.text.v1.TextStyle parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.cg.sdui.components.text.v1.TextStyle parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cg.sdui.components.text.v1.TextStyle parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cg.sdui.components.text.v1.TextStyle parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cg.sdui.components.text.v1.TextStyle prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code components.text.v1.TextStyle}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:components.text.v1.TextStyle)
      com.cg.sdui.components.text.v1.TextStyleOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cg.sdui.components.text.v1.TextProto.internal_static_components_text_v1_TextStyle_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cg.sdui.components.text.v1.TextProto.internal_static_components_text_v1_TextStyle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cg.sdui.components.text.v1.TextStyle.class, com.cg.sdui.components.text.v1.TextStyle.Builder.class);
    }

    // Construct using com.cg.sdui.components.text.v1.TextStyle.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      fullWidth_ = false;
      backgroundColor_ = "";
      txtColor_ = "";
      textAlignment_ = 0;
      maxLines_ = 0;
      maxLenght_ = 0;
      textOverFlow_ = 0;
      androidTypography_ = 0;
      iosTypography_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cg.sdui.components.text.v1.TextProto.internal_static_components_text_v1_TextStyle_descriptor;
    }

    @java.lang.Override
    public com.cg.sdui.components.text.v1.TextStyle getDefaultInstanceForType() {
      return com.cg.sdui.components.text.v1.TextStyle.getDefaultInstance();
    }

    @java.lang.Override
    public com.cg.sdui.components.text.v1.TextStyle build() {
      com.cg.sdui.components.text.v1.TextStyle result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cg.sdui.components.text.v1.TextStyle buildPartial() {
      com.cg.sdui.components.text.v1.TextStyle result = new com.cg.sdui.components.text.v1.TextStyle(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.cg.sdui.components.text.v1.TextStyle result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.fullWidth_ = fullWidth_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.backgroundColor_ = backgroundColor_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.txtColor_ = txtColor_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.textAlignment_ = textAlignment_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.maxLines_ = maxLines_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.maxLenght_ = maxLenght_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.textOverFlow_ = textOverFlow_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.androidTypography_ = androidTypography_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.iosTypography_ = iosTypography_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cg.sdui.components.text.v1.TextStyle) {
        return mergeFrom((com.cg.sdui.components.text.v1.TextStyle)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cg.sdui.components.text.v1.TextStyle other) {
      if (other == com.cg.sdui.components.text.v1.TextStyle.getDefaultInstance()) return this;
      if (other.getFullWidth() != false) {
        setFullWidth(other.getFullWidth());
      }
      if (!other.getBackgroundColor().isEmpty()) {
        backgroundColor_ = other.backgroundColor_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getTxtColor().isEmpty()) {
        txtColor_ = other.txtColor_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.textAlignment_ != 0) {
        setTextAlignmentValue(other.getTextAlignmentValue());
      }
      if (other.getMaxLines() != 0) {
        setMaxLines(other.getMaxLines());
      }
      if (other.getMaxLenght() != 0) {
        setMaxLenght(other.getMaxLenght());
      }
      if (other.textOverFlow_ != 0) {
        setTextOverFlowValue(other.getTextOverFlowValue());
      }
      if (other.hasAndroidTypography()) {
        setAndroidTypography(other.getAndroidTypography());
      }
      if (other.hasIosTypography()) {
        setIosTypography(other.getIosTypography());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              fullWidth_ = input.readBool();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              backgroundColor_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              txtColor_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              textAlignment_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              maxLines_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              maxLenght_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              textOverFlow_ = input.readEnum();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              androidTypography_ = input.readEnum();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              iosTypography_ = input.readEnum();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private boolean fullWidth_ ;
    /**
     * <code>bool fullWidth = 1 [json_name = "fullWidth"];</code>
     * @return The fullWidth.
     */
    @java.lang.Override
    public boolean getFullWidth() {
      return fullWidth_;
    }
    /**
     * <code>bool fullWidth = 1 [json_name = "fullWidth"];</code>
     * @param value The fullWidth to set.
     * @return This builder for chaining.
     */
    public Builder setFullWidth(boolean value) {

      fullWidth_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>bool fullWidth = 1 [json_name = "fullWidth"];</code>
     * @return This builder for chaining.
     */
    public Builder clearFullWidth() {
      bitField0_ = (bitField0_ & ~0x00000001);
      fullWidth_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object backgroundColor_ = "";
    /**
     * <code>string backgroundColor = 2 [json_name = "backgroundColor"];</code>
     * @return The backgroundColor.
     */
    public java.lang.String getBackgroundColor() {
      java.lang.Object ref = backgroundColor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        backgroundColor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string backgroundColor = 2 [json_name = "backgroundColor"];</code>
     * @return The bytes for backgroundColor.
     */
    public com.google.protobuf.ByteString
        getBackgroundColorBytes() {
      java.lang.Object ref = backgroundColor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        backgroundColor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string backgroundColor = 2 [json_name = "backgroundColor"];</code>
     * @param value The backgroundColor to set.
     * @return This builder for chaining.
     */
    public Builder setBackgroundColor(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      backgroundColor_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string backgroundColor = 2 [json_name = "backgroundColor"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBackgroundColor() {
      backgroundColor_ = getDefaultInstance().getBackgroundColor();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string backgroundColor = 2 [json_name = "backgroundColor"];</code>
     * @param value The bytes for backgroundColor to set.
     * @return This builder for chaining.
     */
    public Builder setBackgroundColorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      backgroundColor_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object txtColor_ = "";
    /**
     * <code>string txtColor = 3 [json_name = "txtColor"];</code>
     * @return The txtColor.
     */
    public java.lang.String getTxtColor() {
      java.lang.Object ref = txtColor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        txtColor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string txtColor = 3 [json_name = "txtColor"];</code>
     * @return The bytes for txtColor.
     */
    public com.google.protobuf.ByteString
        getTxtColorBytes() {
      java.lang.Object ref = txtColor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txtColor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string txtColor = 3 [json_name = "txtColor"];</code>
     * @param value The txtColor to set.
     * @return This builder for chaining.
     */
    public Builder setTxtColor(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      txtColor_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string txtColor = 3 [json_name = "txtColor"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTxtColor() {
      txtColor_ = getDefaultInstance().getTxtColor();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string txtColor = 3 [json_name = "txtColor"];</code>
     * @param value The bytes for txtColor to set.
     * @return This builder for chaining.
     */
    public Builder setTxtColorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      txtColor_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int textAlignment_ = 0;
    /**
     * <code>.components.properties.v1.TextAlignment textAlignment = 4 [json_name = "textAlignment"];</code>
     * @return The enum numeric value on the wire for textAlignment.
     */
    @java.lang.Override public int getTextAlignmentValue() {
      return textAlignment_;
    }
    /**
     * <code>.components.properties.v1.TextAlignment textAlignment = 4 [json_name = "textAlignment"];</code>
     * @param value The enum numeric value on the wire for textAlignment to set.
     * @return This builder for chaining.
     */
    public Builder setTextAlignmentValue(int value) {
      textAlignment_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.components.properties.v1.TextAlignment textAlignment = 4 [json_name = "textAlignment"];</code>
     * @return The textAlignment.
     */
    @java.lang.Override
    public com.cg.sdui.components.properties.v1.TextAlignment getTextAlignment() {
      com.cg.sdui.components.properties.v1.TextAlignment result = com.cg.sdui.components.properties.v1.TextAlignment.forNumber(textAlignment_);
      return result == null ? com.cg.sdui.components.properties.v1.TextAlignment.UNRECOGNIZED : result;
    }
    /**
     * <code>.components.properties.v1.TextAlignment textAlignment = 4 [json_name = "textAlignment"];</code>
     * @param value The textAlignment to set.
     * @return This builder for chaining.
     */
    public Builder setTextAlignment(com.cg.sdui.components.properties.v1.TextAlignment value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      textAlignment_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.components.properties.v1.TextAlignment textAlignment = 4 [json_name = "textAlignment"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTextAlignment() {
      bitField0_ = (bitField0_ & ~0x00000008);
      textAlignment_ = 0;
      onChanged();
      return this;
    }

    private int maxLines_ ;
    /**
     * <code>int32 max_lines = 5 [json_name = "maxLines"];</code>
     * @return The maxLines.
     */
    @java.lang.Override
    public int getMaxLines() {
      return maxLines_;
    }
    /**
     * <code>int32 max_lines = 5 [json_name = "maxLines"];</code>
     * @param value The maxLines to set.
     * @return This builder for chaining.
     */
    public Builder setMaxLines(int value) {

      maxLines_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 max_lines = 5 [json_name = "maxLines"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxLines() {
      bitField0_ = (bitField0_ & ~0x00000010);
      maxLines_ = 0;
      onChanged();
      return this;
    }

    private int maxLenght_ ;
    /**
     * <code>int32 max_lenght = 6 [json_name = "maxLenght"];</code>
     * @return The maxLenght.
     */
    @java.lang.Override
    public int getMaxLenght() {
      return maxLenght_;
    }
    /**
     * <code>int32 max_lenght = 6 [json_name = "maxLenght"];</code>
     * @param value The maxLenght to set.
     * @return This builder for chaining.
     */
    public Builder setMaxLenght(int value) {

      maxLenght_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 max_lenght = 6 [json_name = "maxLenght"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxLenght() {
      bitField0_ = (bitField0_ & ~0x00000020);
      maxLenght_ = 0;
      onChanged();
      return this;
    }

    private int textOverFlow_ = 0;
    /**
     * <code>.components.text.v1.TextOverFlow text_over_flow = 7 [json_name = "textOverFlow"];</code>
     * @return The enum numeric value on the wire for textOverFlow.
     */
    @java.lang.Override public int getTextOverFlowValue() {
      return textOverFlow_;
    }
    /**
     * <code>.components.text.v1.TextOverFlow text_over_flow = 7 [json_name = "textOverFlow"];</code>
     * @param value The enum numeric value on the wire for textOverFlow to set.
     * @return This builder for chaining.
     */
    public Builder setTextOverFlowValue(int value) {
      textOverFlow_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.components.text.v1.TextOverFlow text_over_flow = 7 [json_name = "textOverFlow"];</code>
     * @return The textOverFlow.
     */
    @java.lang.Override
    public com.cg.sdui.components.text.v1.TextOverFlow getTextOverFlow() {
      com.cg.sdui.components.text.v1.TextOverFlow result = com.cg.sdui.components.text.v1.TextOverFlow.forNumber(textOverFlow_);
      return result == null ? com.cg.sdui.components.text.v1.TextOverFlow.UNRECOGNIZED : result;
    }
    /**
     * <code>.components.text.v1.TextOverFlow text_over_flow = 7 [json_name = "textOverFlow"];</code>
     * @param value The textOverFlow to set.
     * @return This builder for chaining.
     */
    public Builder setTextOverFlow(com.cg.sdui.components.text.v1.TextOverFlow value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000040;
      textOverFlow_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.components.text.v1.TextOverFlow text_over_flow = 7 [json_name = "textOverFlow"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTextOverFlow() {
      bitField0_ = (bitField0_ & ~0x00000040);
      textOverFlow_ = 0;
      onChanged();
      return this;
    }

    private int androidTypography_ = 0;
    /**
     * <code>optional .components.text.v1.AndroidTypography android_typography = 8 [json_name = "androidTypography"];</code>
     * @return Whether the androidTypography field is set.
     */
    @java.lang.Override public boolean hasAndroidTypography() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional .components.text.v1.AndroidTypography android_typography = 8 [json_name = "androidTypography"];</code>
     * @return The enum numeric value on the wire for androidTypography.
     */
    @java.lang.Override public int getAndroidTypographyValue() {
      return androidTypography_;
    }
    /**
     * <code>optional .components.text.v1.AndroidTypography android_typography = 8 [json_name = "androidTypography"];</code>
     * @param value The enum numeric value on the wire for androidTypography to set.
     * @return This builder for chaining.
     */
    public Builder setAndroidTypographyValue(int value) {
      androidTypography_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>optional .components.text.v1.AndroidTypography android_typography = 8 [json_name = "androidTypography"];</code>
     * @return The androidTypography.
     */
    @java.lang.Override
    public com.cg.sdui.components.text.v1.AndroidTypography getAndroidTypography() {
      com.cg.sdui.components.text.v1.AndroidTypography result = com.cg.sdui.components.text.v1.AndroidTypography.forNumber(androidTypography_);
      return result == null ? com.cg.sdui.components.text.v1.AndroidTypography.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .components.text.v1.AndroidTypography android_typography = 8 [json_name = "androidTypography"];</code>
     * @param value The androidTypography to set.
     * @return This builder for chaining.
     */
    public Builder setAndroidTypography(com.cg.sdui.components.text.v1.AndroidTypography value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000080;
      androidTypography_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .components.text.v1.AndroidTypography android_typography = 8 [json_name = "androidTypography"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAndroidTypography() {
      bitField0_ = (bitField0_ & ~0x00000080);
      androidTypography_ = 0;
      onChanged();
      return this;
    }

    private int iosTypography_ = 0;
    /**
     * <code>optional .components.text.v1.IOSTypography ios_typography = 9 [json_name = "iosTypography"];</code>
     * @return Whether the iosTypography field is set.
     */
    @java.lang.Override public boolean hasIosTypography() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional .components.text.v1.IOSTypography ios_typography = 9 [json_name = "iosTypography"];</code>
     * @return The enum numeric value on the wire for iosTypography.
     */
    @java.lang.Override public int getIosTypographyValue() {
      return iosTypography_;
    }
    /**
     * <code>optional .components.text.v1.IOSTypography ios_typography = 9 [json_name = "iosTypography"];</code>
     * @param value The enum numeric value on the wire for iosTypography to set.
     * @return This builder for chaining.
     */
    public Builder setIosTypographyValue(int value) {
      iosTypography_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>optional .components.text.v1.IOSTypography ios_typography = 9 [json_name = "iosTypography"];</code>
     * @return The iosTypography.
     */
    @java.lang.Override
    public com.cg.sdui.components.text.v1.IOSTypography getIosTypography() {
      com.cg.sdui.components.text.v1.IOSTypography result = com.cg.sdui.components.text.v1.IOSTypography.forNumber(iosTypography_);
      return result == null ? com.cg.sdui.components.text.v1.IOSTypography.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .components.text.v1.IOSTypography ios_typography = 9 [json_name = "iosTypography"];</code>
     * @param value The iosTypography to set.
     * @return This builder for chaining.
     */
    public Builder setIosTypography(com.cg.sdui.components.text.v1.IOSTypography value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000100;
      iosTypography_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .components.text.v1.IOSTypography ios_typography = 9 [json_name = "iosTypography"];</code>
     * @return This builder for chaining.
     */
    public Builder clearIosTypography() {
      bitField0_ = (bitField0_ & ~0x00000100);
      iosTypography_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:components.text.v1.TextStyle)
  }

  // @@protoc_insertion_point(class_scope:components.text.v1.TextStyle)
  private static final com.cg.sdui.components.text.v1.TextStyle DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cg.sdui.components.text.v1.TextStyle();
  }

  public static com.cg.sdui.components.text.v1.TextStyle getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TextStyle>
      PARSER = new com.google.protobuf.AbstractParser<TextStyle>() {
    @java.lang.Override
    public TextStyle parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TextStyle> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TextStyle> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cg.sdui.components.text.v1.TextStyle getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

