// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/text/v1/text.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.components.text.v1;

/**
 * Protobuf enum {@code components.text.v1.TextOverFlow}
 */
public enum TextOverFlow
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>WRAP = 0;</code>
   */
  WRAP(0),
  /**
   * <code>ELIPSES = 1;</code>
   */
  ELIPSES(1),
  /**
   * <code>CLIP = 2;</code>
   */
  CLIP(2),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      TextOverFlow.class.getName());
  }
  /**
   * <code>WRAP = 0;</code>
   */
  public static final int WRAP_VALUE = 0;
  /**
   * <code>ELIPSES = 1;</code>
   */
  public static final int ELIPSES_VALUE = 1;
  /**
   * <code>CLIP = 2;</code>
   */
  public static final int CLIP_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TextOverFlow valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TextOverFlow forNumber(int value) {
    switch (value) {
      case 0: return WRAP;
      case 1: return ELIPSES;
      case 2: return CLIP;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TextOverFlow>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TextOverFlow> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TextOverFlow>() {
          public TextOverFlow findValueByNumber(int number) {
            return TextOverFlow.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.cg.sdui.components.text.v1.TextProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final TextOverFlow[] VALUES = values();

  public static TextOverFlow valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TextOverFlow(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:components.text.v1.TextOverFlow)
}

