// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/properties/v1/action.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.cg.sdui.components.properties.v1;

