// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/properties/v1/action.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.cg.sdui.components.properties.v1;

@kotlin.jvm.JvmName("-initializeaction")
public inline fun action(block: com.cg.sdui.components.properties.v1.ActionKt.Dsl.() -> kotlin.Unit): com.cg.sdui.components.properties.v1.Action =
  com.cg.sdui.components.properties.v1.ActionKt.Dsl._create(com.cg.sdui.components.properties.v1.Action.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `components.properties.v1.Action`
 */
public object ActionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.cg.sdui.components.properties.v1.Action.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.cg.sdui.components.properties.v1.Action.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.cg.sdui.components.properties.v1.Action = _builder.build()

    /**
     * `.components.properties.v1.ActionType action_type = 1 [json_name = "actionType"];`
     */
    public var actionType: com.cg.sdui.components.properties.v1.ActionType
      @kotlin.jvm.JvmName("getActionType")
        get() = _builder.actionType
      @kotlin.jvm.JvmName("setActionType")
        set(value) {
        _builder.actionType = value
      }
    public var actionTypeValue: kotlin.Int
      @kotlin.jvm.JvmName("getActionTypeValue")
        get() = _builder.actionTypeValue
      @kotlin.jvm.JvmName("setActionTypeValue")
        set(value) {
        _builder.actionTypeValue = value
      }
    /**
     * `.components.properties.v1.ActionType action_type = 1 [json_name = "actionType"];`
     */
    public fun clearActionType() {
      _builder.clearActionType()
    }

    /**
     * `string action_value = 2 [json_name = "actionValue"];`
     */
    public var actionValue: kotlin.String
      @kotlin.jvm.JvmName("getActionValue")
        get() = _builder.actionValue
      @kotlin.jvm.JvmName("setActionValue")
        set(value) {
        _builder.actionValue = value
      }
    /**
     * `string action_value = 2 [json_name = "actionValue"];`
     */
    public fun clearActionValue() {
      _builder.clearActionValue()
    }

    /**
     * `string destination = 3 [json_name = "destination"];`
     */
    public var destination: kotlin.String
      @kotlin.jvm.JvmName("getDestination")
        get() = _builder.destination
      @kotlin.jvm.JvmName("setDestination")
        set(value) {
        _builder.destination = value
      }
    /**
     * `string destination = 3 [json_name = "destination"];`
     */
    public fun clearDestination() {
      _builder.clearDestination()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.cg.sdui.components.properties.v1.Action.copy(block: `com.cg.sdui.components.properties.v1`.ActionKt.Dsl.() -> kotlin.Unit): com.cg.sdui.components.properties.v1.Action =
  `com.cg.sdui.components.properties.v1`.ActionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

