// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/properties/v1/shape.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.cg.sdui.components.properties.v1;

@kotlin.jvm.JvmName("-initializeroundedCorners")
public inline fun roundedCorners(block: com.cg.sdui.components.properties.v1.RoundedCornersKt.Dsl.() -> kotlin.Unit): com.cg.sdui.components.properties.v1.RoundedCorners =
  com.cg.sdui.components.properties.v1.RoundedCornersKt.Dsl._create(com.cg.sdui.components.properties.v1.RoundedCorners.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `components.properties.v1.RoundedCorners`
 */
public object RoundedCornersKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.cg.sdui.components.properties.v1.RoundedCorners.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.cg.sdui.components.properties.v1.RoundedCorners.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.cg.sdui.components.properties.v1.RoundedCorners = _builder.build()

    /**
     * `optional int32 all = 1 [json_name = "all"];`
     */
    public var all: kotlin.Int
      @kotlin.jvm.JvmName("getAll")
        get() = _builder.all
      @kotlin.jvm.JvmName("setAll")
        set(value) {
        _builder.all = value
      }
    /**
     * `optional int32 all = 1 [json_name = "all"];`
     */
    public fun clearAll() {
      _builder.clearAll()
    }
    /**
     * `optional int32 all = 1 [json_name = "all"];`
     * @return Whether the all field is set.
     */
    public fun hasAll(): kotlin.Boolean {
      return _builder.hasAll()
    }

    /**
     * `optional int32 left = 2 [json_name = "left"];`
     */
    public var left: kotlin.Int
      @kotlin.jvm.JvmName("getLeft")
        get() = _builder.left
      @kotlin.jvm.JvmName("setLeft")
        set(value) {
        _builder.left = value
      }
    /**
     * `optional int32 left = 2 [json_name = "left"];`
     */
    public fun clearLeft() {
      _builder.clearLeft()
    }
    /**
     * `optional int32 left = 2 [json_name = "left"];`
     * @return Whether the left field is set.
     */
    public fun hasLeft(): kotlin.Boolean {
      return _builder.hasLeft()
    }

    /**
     * `optional int32 right = 3 [json_name = "right"];`
     */
    public var right: kotlin.Int
      @kotlin.jvm.JvmName("getRight")
        get() = _builder.right
      @kotlin.jvm.JvmName("setRight")
        set(value) {
        _builder.right = value
      }
    /**
     * `optional int32 right = 3 [json_name = "right"];`
     */
    public fun clearRight() {
      _builder.clearRight()
    }
    /**
     * `optional int32 right = 3 [json_name = "right"];`
     * @return Whether the right field is set.
     */
    public fun hasRight(): kotlin.Boolean {
      return _builder.hasRight()
    }

    /**
     * `optional int32 top = 4 [json_name = "top"];`
     */
    public var top: kotlin.Int
      @kotlin.jvm.JvmName("getTop")
        get() = _builder.top
      @kotlin.jvm.JvmName("setTop")
        set(value) {
        _builder.top = value
      }
    /**
     * `optional int32 top = 4 [json_name = "top"];`
     */
    public fun clearTop() {
      _builder.clearTop()
    }
    /**
     * `optional int32 top = 4 [json_name = "top"];`
     * @return Whether the top field is set.
     */
    public fun hasTop(): kotlin.Boolean {
      return _builder.hasTop()
    }

    /**
     * `optional int32 bottom = 5 [json_name = "bottom"];`
     */
    public var bottom: kotlin.Int
      @kotlin.jvm.JvmName("getBottom")
        get() = _builder.bottom
      @kotlin.jvm.JvmName("setBottom")
        set(value) {
        _builder.bottom = value
      }
    /**
     * `optional int32 bottom = 5 [json_name = "bottom"];`
     */
    public fun clearBottom() {
      _builder.clearBottom()
    }
    /**
     * `optional int32 bottom = 5 [json_name = "bottom"];`
     * @return Whether the bottom field is set.
     */
    public fun hasBottom(): kotlin.Boolean {
      return _builder.hasBottom()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.cg.sdui.components.properties.v1.RoundedCorners.copy(block: `com.cg.sdui.components.properties.v1`.RoundedCornersKt.Dsl.() -> kotlin.Unit): com.cg.sdui.components.properties.v1.RoundedCorners =
  `com.cg.sdui.components.properties.v1`.RoundedCornersKt.Dsl._create(this.toBuilder()).apply { block() }._build()

