// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/properties/v1/action.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.components.properties.v1;

public final class ActionProto {
  private ActionProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      ActionProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_components_properties_v1_Action_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_components_properties_v1_Action_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%components/properties/v1/action.proto\022" +
      "\030components.properties.v1\"\224\001\n\006Action\022E\n\013" +
      "action_type\030\001 \001(\0162$.components.propertie" +
      "s.v1.ActionTypeR\nactionType\022!\n\014action_va" +
      "lue\030\002 \001(\tR\013actionValue\022 \n\013destination\030\003 " +
      "\001(\tR\013destination**\n\nActionType\022\016\n\nNAVIGA" +
      "TION\020\000\022\014\n\010API_CALL\020\001B\265\001\n$com.cg.sdui.com" +
      "ponents.properties.v1B\013ActionProtoP\001\242\002\003C" +
      "PX\252\002\030Components.Properties.V1\312\002\030Componen" +
      "ts\\Properties\\V1\342\002$Components\\Properties" +
      "\\V1\\GPBMetadata\352\002\032Components::Properties" +
      "::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_components_properties_v1_Action_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_components_properties_v1_Action_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_components_properties_v1_Action_descriptor,
        new java.lang.String[] { "ActionType", "ActionValue", "Destination", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
