// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/properties/v1/shape.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.components.properties.v1;

public interface RoundedCornersOrBuilder extends
    // @@protoc_insertion_point(interface_extends:components.properties.v1.RoundedCorners)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 all = 1 [json_name = "all"];</code>
   * @return Whether the all field is set.
   */
  boolean hasAll();
  /**
   * <code>optional int32 all = 1 [json_name = "all"];</code>
   * @return The all.
   */
  int getAll();

  /**
   * <code>optional int32 left = 2 [json_name = "left"];</code>
   * @return Whether the left field is set.
   */
  boolean hasLeft();
  /**
   * <code>optional int32 left = 2 [json_name = "left"];</code>
   * @return The left.
   */
  int getLeft();

  /**
   * <code>optional int32 right = 3 [json_name = "right"];</code>
   * @return Whether the right field is set.
   */
  boolean hasRight();
  /**
   * <code>optional int32 right = 3 [json_name = "right"];</code>
   * @return The right.
   */
  int getRight();

  /**
   * <code>optional int32 top = 4 [json_name = "top"];</code>
   * @return Whether the top field is set.
   */
  boolean hasTop();
  /**
   * <code>optional int32 top = 4 [json_name = "top"];</code>
   * @return The top.
   */
  int getTop();

  /**
   * <code>optional int32 bottom = 5 [json_name = "bottom"];</code>
   * @return Whether the bottom field is set.
   */
  boolean hasBottom();
  /**
   * <code>optional int32 bottom = 5 [json_name = "bottom"];</code>
   * @return The bottom.
   */
  int getBottom();
}
