// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/properties/v1/shape.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.components.properties.v1;

/**
 * Protobuf type {@code components.properties.v1.Shape}
 */
public final class Shape extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:components.properties.v1.Shape)
    ShapeOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      Shape.class.getName());
  }
  // Use Shape.newBuilder() to construct.
  private Shape(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Shape() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cg.sdui.components.properties.v1.ShapeProto.internal_static_components_properties_v1_Shape_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cg.sdui.components.properties.v1.ShapeProto.internal_static_components_properties_v1_Shape_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cg.sdui.components.properties.v1.Shape.class, com.cg.sdui.components.properties.v1.Shape.Builder.class);
  }

  private int bitField0_;
  public static final int CORNERS_FIELD_NUMBER = 1;
  private com.cg.sdui.components.properties.v1.RoundedCorners corners_;
  /**
   * <code>optional .components.properties.v1.RoundedCorners corners = 1 [json_name = "corners"];</code>
   * @return Whether the corners field is set.
   */
  @java.lang.Override
  public boolean hasCorners() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .components.properties.v1.RoundedCorners corners = 1 [json_name = "corners"];</code>
   * @return The corners.
   */
  @java.lang.Override
  public com.cg.sdui.components.properties.v1.RoundedCorners getCorners() {
    return corners_ == null ? com.cg.sdui.components.properties.v1.RoundedCorners.getDefaultInstance() : corners_;
  }
  /**
   * <code>optional .components.properties.v1.RoundedCorners corners = 1 [json_name = "corners"];</code>
   */
  @java.lang.Override
  public com.cg.sdui.components.properties.v1.RoundedCornersOrBuilder getCornersOrBuilder() {
    return corners_ == null ? com.cg.sdui.components.properties.v1.RoundedCorners.getDefaultInstance() : corners_;
  }

  public static final int BORDER_FIELD_NUMBER = 2;
  private com.cg.sdui.components.properties.v1.Border border_;
  /**
   * <code>optional .components.properties.v1.Border border = 2 [json_name = "border"];</code>
   * @return Whether the border field is set.
   */
  @java.lang.Override
  public boolean hasBorder() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional .components.properties.v1.Border border = 2 [json_name = "border"];</code>
   * @return The border.
   */
  @java.lang.Override
  public com.cg.sdui.components.properties.v1.Border getBorder() {
    return border_ == null ? com.cg.sdui.components.properties.v1.Border.getDefaultInstance() : border_;
  }
  /**
   * <code>optional .components.properties.v1.Border border = 2 [json_name = "border"];</code>
   */
  @java.lang.Override
  public com.cg.sdui.components.properties.v1.BorderOrBuilder getBorderOrBuilder() {
    return border_ == null ? com.cg.sdui.components.properties.v1.Border.getDefaultInstance() : border_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getCorners());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getBorder());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCorners());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getBorder());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cg.sdui.components.properties.v1.Shape)) {
      return super.equals(obj);
    }
    com.cg.sdui.components.properties.v1.Shape other = (com.cg.sdui.components.properties.v1.Shape) obj;

    if (hasCorners() != other.hasCorners()) return false;
    if (hasCorners()) {
      if (!getCorners()
          .equals(other.getCorners())) return false;
    }
    if (hasBorder() != other.hasBorder()) return false;
    if (hasBorder()) {
      if (!getBorder()
          .equals(other.getBorder())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCorners()) {
      hash = (37 * hash) + CORNERS_FIELD_NUMBER;
      hash = (53 * hash) + getCorners().hashCode();
    }
    if (hasBorder()) {
      hash = (37 * hash) + BORDER_FIELD_NUMBER;
      hash = (53 * hash) + getBorder().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cg.sdui.components.properties.v1.Shape parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.sdui.components.properties.v1.Shape parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.sdui.components.properties.v1.Shape parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.sdui.components.properties.v1.Shape parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.sdui.components.properties.v1.Shape parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.sdui.components.properties.v1.Shape parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.sdui.components.properties.v1.Shape parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cg.sdui.components.properties.v1.Shape parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.cg.sdui.components.properties.v1.Shape parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.cg.sdui.components.properties.v1.Shape parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cg.sdui.components.properties.v1.Shape parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cg.sdui.components.properties.v1.Shape parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cg.sdui.components.properties.v1.Shape prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code components.properties.v1.Shape}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:components.properties.v1.Shape)
      com.cg.sdui.components.properties.v1.ShapeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cg.sdui.components.properties.v1.ShapeProto.internal_static_components_properties_v1_Shape_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cg.sdui.components.properties.v1.ShapeProto.internal_static_components_properties_v1_Shape_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cg.sdui.components.properties.v1.Shape.class, com.cg.sdui.components.properties.v1.Shape.Builder.class);
    }

    // Construct using com.cg.sdui.components.properties.v1.Shape.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getCornersFieldBuilder();
        getBorderFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      corners_ = null;
      if (cornersBuilder_ != null) {
        cornersBuilder_.dispose();
        cornersBuilder_ = null;
      }
      border_ = null;
      if (borderBuilder_ != null) {
        borderBuilder_.dispose();
        borderBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cg.sdui.components.properties.v1.ShapeProto.internal_static_components_properties_v1_Shape_descriptor;
    }

    @java.lang.Override
    public com.cg.sdui.components.properties.v1.Shape getDefaultInstanceForType() {
      return com.cg.sdui.components.properties.v1.Shape.getDefaultInstance();
    }

    @java.lang.Override
    public com.cg.sdui.components.properties.v1.Shape build() {
      com.cg.sdui.components.properties.v1.Shape result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cg.sdui.components.properties.v1.Shape buildPartial() {
      com.cg.sdui.components.properties.v1.Shape result = new com.cg.sdui.components.properties.v1.Shape(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.cg.sdui.components.properties.v1.Shape result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.corners_ = cornersBuilder_ == null
            ? corners_
            : cornersBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.border_ = borderBuilder_ == null
            ? border_
            : borderBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cg.sdui.components.properties.v1.Shape) {
        return mergeFrom((com.cg.sdui.components.properties.v1.Shape)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cg.sdui.components.properties.v1.Shape other) {
      if (other == com.cg.sdui.components.properties.v1.Shape.getDefaultInstance()) return this;
      if (other.hasCorners()) {
        mergeCorners(other.getCorners());
      }
      if (other.hasBorder()) {
        mergeBorder(other.getBorder());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getCornersFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getBorderFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.cg.sdui.components.properties.v1.RoundedCorners corners_;
    private com.google.protobuf.SingleFieldBuilder<
        com.cg.sdui.components.properties.v1.RoundedCorners, com.cg.sdui.components.properties.v1.RoundedCorners.Builder, com.cg.sdui.components.properties.v1.RoundedCornersOrBuilder> cornersBuilder_;
    /**
     * <code>optional .components.properties.v1.RoundedCorners corners = 1 [json_name = "corners"];</code>
     * @return Whether the corners field is set.
     */
    public boolean hasCorners() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .components.properties.v1.RoundedCorners corners = 1 [json_name = "corners"];</code>
     * @return The corners.
     */
    public com.cg.sdui.components.properties.v1.RoundedCorners getCorners() {
      if (cornersBuilder_ == null) {
        return corners_ == null ? com.cg.sdui.components.properties.v1.RoundedCorners.getDefaultInstance() : corners_;
      } else {
        return cornersBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .components.properties.v1.RoundedCorners corners = 1 [json_name = "corners"];</code>
     */
    public Builder setCorners(com.cg.sdui.components.properties.v1.RoundedCorners value) {
      if (cornersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        corners_ = value;
      } else {
        cornersBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .components.properties.v1.RoundedCorners corners = 1 [json_name = "corners"];</code>
     */
    public Builder setCorners(
        com.cg.sdui.components.properties.v1.RoundedCorners.Builder builderForValue) {
      if (cornersBuilder_ == null) {
        corners_ = builderForValue.build();
      } else {
        cornersBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .components.properties.v1.RoundedCorners corners = 1 [json_name = "corners"];</code>
     */
    public Builder mergeCorners(com.cg.sdui.components.properties.v1.RoundedCorners value) {
      if (cornersBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          corners_ != null &&
          corners_ != com.cg.sdui.components.properties.v1.RoundedCorners.getDefaultInstance()) {
          getCornersBuilder().mergeFrom(value);
        } else {
          corners_ = value;
        }
      } else {
        cornersBuilder_.mergeFrom(value);
      }
      if (corners_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .components.properties.v1.RoundedCorners corners = 1 [json_name = "corners"];</code>
     */
    public Builder clearCorners() {
      bitField0_ = (bitField0_ & ~0x00000001);
      corners_ = null;
      if (cornersBuilder_ != null) {
        cornersBuilder_.dispose();
        cornersBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .components.properties.v1.RoundedCorners corners = 1 [json_name = "corners"];</code>
     */
    public com.cg.sdui.components.properties.v1.RoundedCorners.Builder getCornersBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getCornersFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .components.properties.v1.RoundedCorners corners = 1 [json_name = "corners"];</code>
     */
    public com.cg.sdui.components.properties.v1.RoundedCornersOrBuilder getCornersOrBuilder() {
      if (cornersBuilder_ != null) {
        return cornersBuilder_.getMessageOrBuilder();
      } else {
        return corners_ == null ?
            com.cg.sdui.components.properties.v1.RoundedCorners.getDefaultInstance() : corners_;
      }
    }
    /**
     * <code>optional .components.properties.v1.RoundedCorners corners = 1 [json_name = "corners"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.cg.sdui.components.properties.v1.RoundedCorners, com.cg.sdui.components.properties.v1.RoundedCorners.Builder, com.cg.sdui.components.properties.v1.RoundedCornersOrBuilder> 
        getCornersFieldBuilder() {
      if (cornersBuilder_ == null) {
        cornersBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.cg.sdui.components.properties.v1.RoundedCorners, com.cg.sdui.components.properties.v1.RoundedCorners.Builder, com.cg.sdui.components.properties.v1.RoundedCornersOrBuilder>(
                getCorners(),
                getParentForChildren(),
                isClean());
        corners_ = null;
      }
      return cornersBuilder_;
    }

    private com.cg.sdui.components.properties.v1.Border border_;
    private com.google.protobuf.SingleFieldBuilder<
        com.cg.sdui.components.properties.v1.Border, com.cg.sdui.components.properties.v1.Border.Builder, com.cg.sdui.components.properties.v1.BorderOrBuilder> borderBuilder_;
    /**
     * <code>optional .components.properties.v1.Border border = 2 [json_name = "border"];</code>
     * @return Whether the border field is set.
     */
    public boolean hasBorder() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional .components.properties.v1.Border border = 2 [json_name = "border"];</code>
     * @return The border.
     */
    public com.cg.sdui.components.properties.v1.Border getBorder() {
      if (borderBuilder_ == null) {
        return border_ == null ? com.cg.sdui.components.properties.v1.Border.getDefaultInstance() : border_;
      } else {
        return borderBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .components.properties.v1.Border border = 2 [json_name = "border"];</code>
     */
    public Builder setBorder(com.cg.sdui.components.properties.v1.Border value) {
      if (borderBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        border_ = value;
      } else {
        borderBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional .components.properties.v1.Border border = 2 [json_name = "border"];</code>
     */
    public Builder setBorder(
        com.cg.sdui.components.properties.v1.Border.Builder builderForValue) {
      if (borderBuilder_ == null) {
        border_ = builderForValue.build();
      } else {
        borderBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional .components.properties.v1.Border border = 2 [json_name = "border"];</code>
     */
    public Builder mergeBorder(com.cg.sdui.components.properties.v1.Border value) {
      if (borderBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          border_ != null &&
          border_ != com.cg.sdui.components.properties.v1.Border.getDefaultInstance()) {
          getBorderBuilder().mergeFrom(value);
        } else {
          border_ = value;
        }
      } else {
        borderBuilder_.mergeFrom(value);
      }
      if (border_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .components.properties.v1.Border border = 2 [json_name = "border"];</code>
     */
    public Builder clearBorder() {
      bitField0_ = (bitField0_ & ~0x00000002);
      border_ = null;
      if (borderBuilder_ != null) {
        borderBuilder_.dispose();
        borderBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .components.properties.v1.Border border = 2 [json_name = "border"];</code>
     */
    public com.cg.sdui.components.properties.v1.Border.Builder getBorderBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getBorderFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .components.properties.v1.Border border = 2 [json_name = "border"];</code>
     */
    public com.cg.sdui.components.properties.v1.BorderOrBuilder getBorderOrBuilder() {
      if (borderBuilder_ != null) {
        return borderBuilder_.getMessageOrBuilder();
      } else {
        return border_ == null ?
            com.cg.sdui.components.properties.v1.Border.getDefaultInstance() : border_;
      }
    }
    /**
     * <code>optional .components.properties.v1.Border border = 2 [json_name = "border"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.cg.sdui.components.properties.v1.Border, com.cg.sdui.components.properties.v1.Border.Builder, com.cg.sdui.components.properties.v1.BorderOrBuilder> 
        getBorderFieldBuilder() {
      if (borderBuilder_ == null) {
        borderBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.cg.sdui.components.properties.v1.Border, com.cg.sdui.components.properties.v1.Border.Builder, com.cg.sdui.components.properties.v1.BorderOrBuilder>(
                getBorder(),
                getParentForChildren(),
                isClean());
        border_ = null;
      }
      return borderBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:components.properties.v1.Shape)
  }

  // @@protoc_insertion_point(class_scope:components.properties.v1.Shape)
  private static final com.cg.sdui.components.properties.v1.Shape DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cg.sdui.components.properties.v1.Shape();
  }

  public static com.cg.sdui.components.properties.v1.Shape getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Shape>
      PARSER = new com.google.protobuf.AbstractParser<Shape>() {
    @java.lang.Override
    public Shape parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Shape> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Shape> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cg.sdui.components.properties.v1.Shape getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

