// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/properties/v1/text_alignment.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.components.properties.v1;

/**
 * Protobuf enum {@code components.properties.v1.TextAlignment}
 */
public enum TextAlignment
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>CENTER = 0;</code>
   */
  CENTER(0),
  /**
   * <code>START = 1;</code>
   */
  START(1),
  /**
   * <code>END = 2;</code>
   */
  END(2),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      TextAlignment.class.getName());
  }
  /**
   * <code>CENTER = 0;</code>
   */
  public static final int CENTER_VALUE = 0;
  /**
   * <code>START = 1;</code>
   */
  public static final int START_VALUE = 1;
  /**
   * <code>END = 2;</code>
   */
  public static final int END_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TextAlignment valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static TextAlignment forNumber(int value) {
    switch (value) {
      case 0: return CENTER;
      case 1: return START;
      case 2: return END;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TextAlignment>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TextAlignment> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TextAlignment>() {
          public TextAlignment findValueByNumber(int number) {
            return TextAlignment.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.cg.sdui.components.properties.v1.TextAlignmentProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final TextAlignment[] VALUES = values();

  public static TextAlignment valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private TextAlignment(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:components.properties.v1.TextAlignment)
}

