// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/properties/v1/text_alignment.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.components.properties.v1;

public final class TextAlignmentProto {
  private TextAlignmentProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      TextAlignmentProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-components/properties/v1/text_alignmen" +
      "t.proto\022\030components.properties.v1*/\n\rTex" +
      "tAlignment\022\n\n\006CENTER\020\000\022\t\n\005START\020\001\022\007\n\003END" +
      "\020\002B\274\001\n$com.cg.sdui.components.properties" +
      ".v1B\022TextAlignmentProtoP\001\242\002\003CPX\252\002\030Compon" +
      "ents.Properties.V1\312\002\030Components\\Properti" +
      "es\\V1\342\002$Components\\Properties\\V1\\GPBMeta" +
      "data\352\002\032Components::Properties::V1b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
