// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/properties/v1/ui_component.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.components.properties.v1;

public final class UiComponentProto {
  private UiComponentProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      UiComponentProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_components_properties_v1_SDUIComponent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_components_properties_v1_SDUIComponent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+components/properties/v1/ui_component." +
      "proto\022\030components.properties.v1\032\031google/" +
      "protobuf/any.proto\"v\n\rSDUIComponent\022;\n\004t" +
      "ype\030\001 \001(\0162\'.components.properties.v1.Com" +
      "ponentTypeR\004type\022(\n\004data\030\002 \001(\0132\024.google." +
      "protobuf.AnyR\004data*_\n\rComponentType\022\n\n\006B" +
      "UTTON\020\000\022\010\n\004TEXT\020\001\022\t\n\005IMAGE\020\002\022\016\n\nOFFER_CA" +
      "RD\020\003\022\n\n\006COLUMN\020\004\022\007\n\003ROW\020\005\022\010\n\004GRID\020\006B\272\001\n$" +
      "com.cg.sdui.components.properties.v1B\020Ui" +
      "ComponentProtoP\001\242\002\003CPX\252\002\030Components.Prop" +
      "erties.V1\312\002\030Components\\Properties\\V1\342\002$C" +
      "omponents\\Properties\\V1\\GPBMetadata\352\002\032Co" +
      "mponents::Properties::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_components_properties_v1_SDUIComponent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_components_properties_v1_SDUIComponent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_components_properties_v1_SDUIComponent_descriptor,
        new java.lang.String[] { "Type", "Data", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
