// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/V1/button.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.components;

/**
 * Protobuf enum {@code components.ActionType}
 */
public enum ActionType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>ACTION_NAVIGATION = 0;</code>
   */
  ACTION_NAVIGATION(0),
  /**
   * <code>ACTION_TYPE_API_CALL = 1;</code>
   */
  ACTION_TYPE_API_CALL(1),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      ActionType.class.getName());
  }
  /**
   * <code>ACTION_NAVIGATION = 0;</code>
   */
  public static final int ACTION_NAVIGATION_VALUE = 0;
  /**
   * <code>ACTION_TYPE_API_CALL = 1;</code>
   */
  public static final int ACTION_TYPE_API_CALL_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ActionType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ActionType forNumber(int value) {
    switch (value) {
      case 0: return ACTION_NAVIGATION;
      case 1: return ACTION_TYPE_API_CALL;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ActionType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ActionType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ActionType>() {
          public ActionType findValueByNumber(int number) {
            return ActionType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.cg.sdui.components.ButtonProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final ActionType[] VALUES = values();

  public static ActionType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ActionType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:components.ActionType)
}

