// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/V1/button.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.components;

public final class ButtonProto {
  private ButtonProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      ButtonProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_components_SduiButton_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_components_SduiButton_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_components_Action_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_components_Action_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032components/V1/button.proto\022\ncomponents" +
      "\"h\n\nSduiButton\022\024\n\005label\030\001 \001(\tR\005label\022\030\n\007" +
      "enabled\030\002 \001(\010R\007enabled\022*\n\006action\030\003 \001(\0132\022" +
      ".components.ActionR\006action\"d\n\006Action\0227\n\013" +
      "action_type\030\001 \001(\0162\026.components.ActionTyp" +
      "eR\nactionType\022!\n\014action_value\030\002 \001(\tR\013act" +
      "ionValue*=\n\nActionType\022\025\n\021ACTION_NAVIGAT" +
      "ION\020\000\022\030\n\024ACTION_TYPE_API_CALL\020\001Bm\n\026com.c" +
      "g.sdui.componentsB\013ButtonProtoP\001\242\002\003CXX\252\002" +
      "\nComponents\312\002\nComponents\342\002\026Components\\GP" +
      "BMetadata\352\002\nComponentsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_components_SduiButton_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_components_SduiButton_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_components_SduiButton_descriptor,
        new java.lang.String[] { "Label", "Enabled", "Action", });
    internal_static_components_Action_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_components_Action_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_components_Action_descriptor,
        new java.lang.String[] { "ActionType", "ActionValue", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
