// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/V1/button.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.components;

public interface SduiButtonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:components.SduiButton)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string label = 1 [json_name = "label"];</code>
   * @return The label.
   */
  java.lang.String getLabel();
  /**
   * <code>string label = 1 [json_name = "label"];</code>
   * @return The bytes for label.
   */
  com.google.protobuf.ByteString
      getLabelBytes();

  /**
   * <code>bool enabled = 2 [json_name = "enabled"];</code>
   * @return The enabled.
   */
  boolean getEnabled();

  /**
   * <code>.components.Action action = 3 [json_name = "action"];</code>
   * @return Whether the action field is set.
   */
  boolean hasAction();
  /**
   * <code>.components.Action action = 3 [json_name = "action"];</code>
   * @return The action.
   */
  com.cg.sdui.components.Action getAction();
  /**
   * <code>.components.Action action = 3 [json_name = "action"];</code>
   */
  com.cg.sdui.components.ActionOrBuilder getActionOrBuilder();
}
