// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/menu/menu_item.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.cg.sdui.components.menu;

@kotlin.jvm.JvmName("-initializemenuItem")
public inline fun menuItem(block: com.cg.sdui.components.menu.MenuItemKt.Dsl.() -> kotlin.Unit): com.cg.sdui.components.menu.MenuItem =
  com.cg.sdui.components.menu.MenuItemKt.Dsl._create(com.cg.sdui.components.menu.MenuItem.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `components.menu.MenuItem`
 */
public object MenuItemKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.cg.sdui.components.menu.MenuItem.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.cg.sdui.components.menu.MenuItem.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.cg.sdui.components.menu.MenuItem = _builder.build()

    /**
     * `.components.icon.v1.Icon leading_icon = 1 [json_name = "leadingIcon"];`
     */
    public var leadingIcon: com.cg.sdui.components.icon.v1.Icon
      @kotlin.jvm.JvmName("getLeadingIcon")
        get() = _builder.leadingIcon
      @kotlin.jvm.JvmName("setLeadingIcon")
        set(value) {
        _builder.leadingIcon = value
      }
    /**
     * `.components.icon.v1.Icon leading_icon = 1 [json_name = "leadingIcon"];`
     */
    public fun clearLeadingIcon() {
      _builder.clearLeadingIcon()
    }
    /**
     * `.components.icon.v1.Icon leading_icon = 1 [json_name = "leadingIcon"];`
     * @return Whether the leadingIcon field is set.
     */
    public fun hasLeadingIcon(): kotlin.Boolean {
      return _builder.hasLeadingIcon()
    }

    public val MenuItemKt.Dsl.leadingIconOrNull: com.cg.sdui.components.icon.v1.Icon?
      get() = _builder.leadingIconOrNull

    /**
     * `string title = 2 [json_name = "title"];`
     */
    public var title: kotlin.String
      @kotlin.jvm.JvmName("getTitle")
        get() = _builder.title
      @kotlin.jvm.JvmName("setTitle")
        set(value) {
        _builder.title = value
      }
    /**
     * `string title = 2 [json_name = "title"];`
     */
    public fun clearTitle() {
      _builder.clearTitle()
    }

    /**
     * `.components.icon.v1.Icon trailing_icon = 3 [json_name = "trailingIcon"];`
     */
    public var trailingIcon: com.cg.sdui.components.icon.v1.Icon
      @kotlin.jvm.JvmName("getTrailingIcon")
        get() = _builder.trailingIcon
      @kotlin.jvm.JvmName("setTrailingIcon")
        set(value) {
        _builder.trailingIcon = value
      }
    /**
     * `.components.icon.v1.Icon trailing_icon = 3 [json_name = "trailingIcon"];`
     */
    public fun clearTrailingIcon() {
      _builder.clearTrailingIcon()
    }
    /**
     * `.components.icon.v1.Icon trailing_icon = 3 [json_name = "trailingIcon"];`
     * @return Whether the trailingIcon field is set.
     */
    public fun hasTrailingIcon(): kotlin.Boolean {
      return _builder.hasTrailingIcon()
    }

    public val MenuItemKt.Dsl.trailingIconOrNull: com.cg.sdui.components.icon.v1.Icon?
      get() = _builder.trailingIconOrNull

    /**
     * `.components.properties.v1.Action action = 4 [json_name = "action"];`
     */
    public var action: com.cg.sdui.components.properties.v1.Action
      @kotlin.jvm.JvmName("getAction")
        get() = _builder.action
      @kotlin.jvm.JvmName("setAction")
        set(value) {
        _builder.action = value
      }
    /**
     * `.components.properties.v1.Action action = 4 [json_name = "action"];`
     */
    public fun clearAction() {
      _builder.clearAction()
    }
    /**
     * `.components.properties.v1.Action action = 4 [json_name = "action"];`
     * @return Whether the action field is set.
     */
    public fun hasAction(): kotlin.Boolean {
      return _builder.hasAction()
    }

    public val MenuItemKt.Dsl.actionOrNull: com.cg.sdui.components.properties.v1.Action?
      get() = _builder.actionOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.cg.sdui.components.menu.MenuItem.copy(block: `com.cg.sdui.components.menu`.MenuItemKt.Dsl.() -> kotlin.Unit): com.cg.sdui.components.menu.MenuItem =
  `com.cg.sdui.components.menu`.MenuItemKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.cg.sdui.components.menu.MenuItemOrBuilder.leadingIconOrNull: com.cg.sdui.components.icon.v1.Icon?
  get() = if (hasLeadingIcon()) getLeadingIcon() else null

public val com.cg.sdui.components.menu.MenuItemOrBuilder.trailingIconOrNull: com.cg.sdui.components.icon.v1.Icon?
  get() = if (hasTrailingIcon()) getTrailingIcon() else null

public val com.cg.sdui.components.menu.MenuItemOrBuilder.actionOrNull: com.cg.sdui.components.properties.v1.Action?
  get() = if (hasAction()) getAction() else null

