// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/V1/button.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.cg.sdui.components;

@kotlin.jvm.JvmName("-initializesduiButton")
public inline fun sduiButton(block: com.cg.sdui.components.SduiButtonKt.Dsl.() -> kotlin.Unit): com.cg.sdui.components.SduiButton =
  com.cg.sdui.components.SduiButtonKt.Dsl._create(com.cg.sdui.components.SduiButton.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `components.SduiButton`
 */
public object SduiButtonKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.cg.sdui.components.SduiButton.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.cg.sdui.components.SduiButton.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.cg.sdui.components.SduiButton = _builder.build()

    /**
     * `string label = 1 [json_name = "label"];`
     */
    public var label: kotlin.String
      @kotlin.jvm.JvmName("getLabel")
        get() = _builder.label
      @kotlin.jvm.JvmName("setLabel")
        set(value) {
        _builder.label = value
      }
    /**
     * `string label = 1 [json_name = "label"];`
     */
    public fun clearLabel() {
      _builder.clearLabel()
    }

    /**
     * `bool enabled = 2 [json_name = "enabled"];`
     */
    public var enabled: kotlin.Boolean
      @kotlin.jvm.JvmName("getEnabled")
        get() = _builder.enabled
      @kotlin.jvm.JvmName("setEnabled")
        set(value) {
        _builder.enabled = value
      }
    /**
     * `bool enabled = 2 [json_name = "enabled"];`
     */
    public fun clearEnabled() {
      _builder.clearEnabled()
    }

    /**
     * `.components.Action action = 3 [json_name = "action"];`
     */
    public var action: com.cg.sdui.components.Action
      @kotlin.jvm.JvmName("getAction")
        get() = _builder.action
      @kotlin.jvm.JvmName("setAction")
        set(value) {
        _builder.action = value
      }
    /**
     * `.components.Action action = 3 [json_name = "action"];`
     */
    public fun clearAction() {
      _builder.clearAction()
    }
    /**
     * `.components.Action action = 3 [json_name = "action"];`
     * @return Whether the action field is set.
     */
    public fun hasAction(): kotlin.Boolean {
      return _builder.hasAction()
    }

    public val SduiButtonKt.Dsl.actionOrNull: com.cg.sdui.components.Action?
      get() = _builder.actionOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.cg.sdui.components.SduiButton.copy(block: `com.cg.sdui.components`.SduiButtonKt.Dsl.() -> kotlin.Unit): com.cg.sdui.components.SduiButton =
  `com.cg.sdui.components`.SduiButtonKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.cg.sdui.components.SduiButtonOrBuilder.actionOrNull: com.cg.sdui.components.Action?
  get() = if (hasAction()) getAction() else null

