// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/icon/v1/icon.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.components.icon.v1;

public final class IconProto {
  private IconProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      IconProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_components_icon_v1_Icon_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_components_icon_v1_Icon_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035components/icon/v1/icon.proto\022\022compone" +
      "nts.icon.v1\"@\n\004Icon\022\022\n\004size\030\001 \001(\005R\004size\022" +
      "\022\n\004tint\030\002 \001(\tR\004tint\022\020\n\003src\030\003 \001(\tR\003srcB\225\001" +
      "\n\036com.cg.sdui.components.icon.v1B\tIconPr" +
      "otoP\001\242\002\003CIX\252\002\022Components.Icon.V1\312\002\022Compo" +
      "nents\\Icon\\V1\342\002\036Components\\Icon\\V1\\GPBMe" +
      "tadata\352\002\024Components::Icon::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_components_icon_v1_Icon_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_components_icon_v1_Icon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_components_icon_v1_Icon_descriptor,
        new java.lang.String[] { "Size", "Tint", "Src", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
