// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/icon/v1/icon.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.components.icon.v1;

/**
 * Protobuf type {@code components.icon.v1.Icon}
 */
public final class Icon extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:components.icon.v1.Icon)
    IconOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      Icon.class.getName());
  }
  // Use Icon.newBuilder() to construct.
  private Icon(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Icon() {
    tint_ = "";
    src_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cg.sdui.components.icon.v1.IconProto.internal_static_components_icon_v1_Icon_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cg.sdui.components.icon.v1.IconProto.internal_static_components_icon_v1_Icon_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cg.sdui.components.icon.v1.Icon.class, com.cg.sdui.components.icon.v1.Icon.Builder.class);
  }

  public static final int SIZE_FIELD_NUMBER = 1;
  private int size_ = 0;
  /**
   * <code>int32 size = 1 [json_name = "size"];</code>
   * @return The size.
   */
  @java.lang.Override
  public int getSize() {
    return size_;
  }

  public static final int TINT_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object tint_ = "";
  /**
   * <code>string tint = 2 [json_name = "tint"];</code>
   * @return The tint.
   */
  @java.lang.Override
  public java.lang.String getTint() {
    java.lang.Object ref = tint_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tint_ = s;
      return s;
    }
  }
  /**
   * <code>string tint = 2 [json_name = "tint"];</code>
   * @return The bytes for tint.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTintBytes() {
    java.lang.Object ref = tint_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tint_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SRC_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object src_ = "";
  /**
   * <code>string src = 3 [json_name = "src"];</code>
   * @return The src.
   */
  @java.lang.Override
  public java.lang.String getSrc() {
    java.lang.Object ref = src_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      src_ = s;
      return s;
    }
  }
  /**
   * <code>string src = 3 [json_name = "src"];</code>
   * @return The bytes for src.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSrcBytes() {
    java.lang.Object ref = src_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      src_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (size_ != 0) {
      output.writeInt32(1, size_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tint_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, tint_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(src_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, src_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (size_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, size_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(tint_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, tint_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(src_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, src_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cg.sdui.components.icon.v1.Icon)) {
      return super.equals(obj);
    }
    com.cg.sdui.components.icon.v1.Icon other = (com.cg.sdui.components.icon.v1.Icon) obj;

    if (getSize()
        != other.getSize()) return false;
    if (!getTint()
        .equals(other.getTint())) return false;
    if (!getSrc()
        .equals(other.getSrc())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getSize();
    hash = (37 * hash) + TINT_FIELD_NUMBER;
    hash = (53 * hash) + getTint().hashCode();
    hash = (37 * hash) + SRC_FIELD_NUMBER;
    hash = (53 * hash) + getSrc().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cg.sdui.components.icon.v1.Icon parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.sdui.components.icon.v1.Icon parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.sdui.components.icon.v1.Icon parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.sdui.components.icon.v1.Icon parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.sdui.components.icon.v1.Icon parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.sdui.components.icon.v1.Icon parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.sdui.components.icon.v1.Icon parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cg.sdui.components.icon.v1.Icon parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.cg.sdui.components.icon.v1.Icon parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.cg.sdui.components.icon.v1.Icon parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cg.sdui.components.icon.v1.Icon parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cg.sdui.components.icon.v1.Icon parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cg.sdui.components.icon.v1.Icon prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code components.icon.v1.Icon}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:components.icon.v1.Icon)
      com.cg.sdui.components.icon.v1.IconOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cg.sdui.components.icon.v1.IconProto.internal_static_components_icon_v1_Icon_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cg.sdui.components.icon.v1.IconProto.internal_static_components_icon_v1_Icon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cg.sdui.components.icon.v1.Icon.class, com.cg.sdui.components.icon.v1.Icon.Builder.class);
    }

    // Construct using com.cg.sdui.components.icon.v1.Icon.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      size_ = 0;
      tint_ = "";
      src_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cg.sdui.components.icon.v1.IconProto.internal_static_components_icon_v1_Icon_descriptor;
    }

    @java.lang.Override
    public com.cg.sdui.components.icon.v1.Icon getDefaultInstanceForType() {
      return com.cg.sdui.components.icon.v1.Icon.getDefaultInstance();
    }

    @java.lang.Override
    public com.cg.sdui.components.icon.v1.Icon build() {
      com.cg.sdui.components.icon.v1.Icon result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cg.sdui.components.icon.v1.Icon buildPartial() {
      com.cg.sdui.components.icon.v1.Icon result = new com.cg.sdui.components.icon.v1.Icon(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.cg.sdui.components.icon.v1.Icon result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.size_ = size_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.tint_ = tint_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.src_ = src_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cg.sdui.components.icon.v1.Icon) {
        return mergeFrom((com.cg.sdui.components.icon.v1.Icon)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cg.sdui.components.icon.v1.Icon other) {
      if (other == com.cg.sdui.components.icon.v1.Icon.getDefaultInstance()) return this;
      if (other.getSize() != 0) {
        setSize(other.getSize());
      }
      if (!other.getTint().isEmpty()) {
        tint_ = other.tint_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getSrc().isEmpty()) {
        src_ = other.src_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              size_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              tint_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              src_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int size_ ;
    /**
     * <code>int32 size = 1 [json_name = "size"];</code>
     * @return The size.
     */
    @java.lang.Override
    public int getSize() {
      return size_;
    }
    /**
     * <code>int32 size = 1 [json_name = "size"];</code>
     * @param value The size to set.
     * @return This builder for chaining.
     */
    public Builder setSize(int value) {

      size_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 size = 1 [json_name = "size"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSize() {
      bitField0_ = (bitField0_ & ~0x00000001);
      size_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object tint_ = "";
    /**
     * <code>string tint = 2 [json_name = "tint"];</code>
     * @return The tint.
     */
    public java.lang.String getTint() {
      java.lang.Object ref = tint_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tint_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tint = 2 [json_name = "tint"];</code>
     * @return The bytes for tint.
     */
    public com.google.protobuf.ByteString
        getTintBytes() {
      java.lang.Object ref = tint_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tint_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tint = 2 [json_name = "tint"];</code>
     * @param value The tint to set.
     * @return This builder for chaining.
     */
    public Builder setTint(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      tint_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string tint = 2 [json_name = "tint"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTint() {
      tint_ = getDefaultInstance().getTint();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string tint = 2 [json_name = "tint"];</code>
     * @param value The bytes for tint to set.
     * @return This builder for chaining.
     */
    public Builder setTintBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      tint_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object src_ = "";
    /**
     * <code>string src = 3 [json_name = "src"];</code>
     * @return The src.
     */
    public java.lang.String getSrc() {
      java.lang.Object ref = src_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        src_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string src = 3 [json_name = "src"];</code>
     * @return The bytes for src.
     */
    public com.google.protobuf.ByteString
        getSrcBytes() {
      java.lang.Object ref = src_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        src_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string src = 3 [json_name = "src"];</code>
     * @param value The src to set.
     * @return This builder for chaining.
     */
    public Builder setSrc(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      src_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string src = 3 [json_name = "src"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSrc() {
      src_ = getDefaultInstance().getSrc();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string src = 3 [json_name = "src"];</code>
     * @param value The bytes for src to set.
     * @return This builder for chaining.
     */
    public Builder setSrcBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      src_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:components.icon.v1.Icon)
  }

  // @@protoc_insertion_point(class_scope:components.icon.v1.Icon)
  private static final com.cg.sdui.components.icon.v1.Icon DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cg.sdui.components.icon.v1.Icon();
  }

  public static com.cg.sdui.components.icon.v1.Icon getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Icon>
      PARSER = new com.google.protobuf.AbstractParser<Icon>() {
    @java.lang.Override
    public Icon parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Icon> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Icon> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cg.sdui.components.icon.v1.Icon getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

