// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/image/v1/image.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.components.image.v1;

public final class ImageProto {
  private ImageProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      ImageProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_components_image_v1_SDUIImageView_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_components_image_v1_SDUIImageView_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_components_image_v1_ImageStyle_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_components_image_v1_ImageStyle_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037components/image/v1/image.proto\022\023compo" +
      "nents.image.v1\032%components/properties/v1" +
      "/action.proto\"\275\001\n\rSDUIImageView\022\020\n\003src\030\001" +
      " \001(\tR\003src\022\031\n\010alt_text\030\002 \001(\tR\007altText\0225\n\005" +
      "style\030\003 \001(\0132\037.components.image.v1.ImageS" +
      "tyleR\005style\022=\n\006action\030\004 \001(\0132 .components" +
      ".properties.v1.ActionH\000R\006action\210\001\001B\t\n\007_a" +
      "ction\"i\n\nImageStyle\022\034\n\tfullWidth\030\001 \001(\010R\t" +
      "fullWidth\022=\n\nscale_type\030\002 \001(\0162\036.componen" +
      "ts.image.v1.ScaleTypeR\tscaleType*D\n\tScal" +
      "eType\022\016\n\nFIT_BOUNDS\020\000\022\010\n\004CROP\020\001\022\r\n\tFIT_W" +
      "IDTH\020\002\022\016\n\nFIT_HEIGHT\020\003B\233\001\n\037com.cg.sdui.c" +
      "omponents.image.v1B\nImageProtoP\001\242\002\003CIX\252\002" +
      "\023Components.Image.V1\312\002\023Components\\Image\\" +
      "V1\342\002\037Components\\Image\\V1\\GPBMetadata\352\002\025C" +
      "omponents::Image::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.cg.sdui.components.properties.v1.ActionProto.getDescriptor(),
        });
    internal_static_components_image_v1_SDUIImageView_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_components_image_v1_SDUIImageView_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_components_image_v1_SDUIImageView_descriptor,
        new java.lang.String[] { "Src", "AltText", "Style", "Action", });
    internal_static_components_image_v1_ImageStyle_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_components_image_v1_ImageStyle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_components_image_v1_ImageStyle_descriptor,
        new java.lang.String[] { "FullWidth", "ScaleType", });
    descriptor.resolveAllFeaturesImmutable();
    com.cg.sdui.components.properties.v1.ActionProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
