// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/image/v1/image.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.components.image.v1;

/**
 * Protobuf enum {@code components.image.v1.ScaleType}
 */
public enum ScaleType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>FIT_BOUNDS = 0;</code>
   */
  FIT_BOUNDS(0),
  /**
   * <code>CROP = 1;</code>
   */
  CROP(1),
  /**
   * <code>FIT_WIDTH = 2;</code>
   */
  FIT_WIDTH(2),
  /**
   * <code>FIT_HEIGHT = 3;</code>
   */
  FIT_HEIGHT(3),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      ScaleType.class.getName());
  }
  /**
   * <code>FIT_BOUNDS = 0;</code>
   */
  public static final int FIT_BOUNDS_VALUE = 0;
  /**
   * <code>CROP = 1;</code>
   */
  public static final int CROP_VALUE = 1;
  /**
   * <code>FIT_WIDTH = 2;</code>
   */
  public static final int FIT_WIDTH_VALUE = 2;
  /**
   * <code>FIT_HEIGHT = 3;</code>
   */
  public static final int FIT_HEIGHT_VALUE = 3;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ScaleType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ScaleType forNumber(int value) {
    switch (value) {
      case 0: return FIT_BOUNDS;
      case 1: return CROP;
      case 2: return FIT_WIDTH;
      case 3: return FIT_HEIGHT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ScaleType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ScaleType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ScaleType>() {
          public ScaleType findValueByNumber(int number) {
            return ScaleType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.cg.sdui.components.image.v1.ImageProto.getDescriptor().getEnumTypes().get(0);
  }

  private static final ScaleType[] VALUES = values();

  public static ScaleType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ScaleType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:components.image.v1.ScaleType)
}

