// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/image/v1/image.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.components.image.v1;

public interface SDUIImageViewOrBuilder extends
    // @@protoc_insertion_point(interface_extends:components.image.v1.SDUIImageView)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string src = 1 [json_name = "src"];</code>
   * @return The src.
   */
  java.lang.String getSrc();
  /**
   * <code>string src = 1 [json_name = "src"];</code>
   * @return The bytes for src.
   */
  com.google.protobuf.ByteString
      getSrcBytes();

  /**
   * <code>string alt_text = 2 [json_name = "altText"];</code>
   * @return The altText.
   */
  java.lang.String getAltText();
  /**
   * <code>string alt_text = 2 [json_name = "altText"];</code>
   * @return The bytes for altText.
   */
  com.google.protobuf.ByteString
      getAltTextBytes();

  /**
   * <code>.components.image.v1.ImageStyle style = 3 [json_name = "style"];</code>
   * @return Whether the style field is set.
   */
  boolean hasStyle();
  /**
   * <code>.components.image.v1.ImageStyle style = 3 [json_name = "style"];</code>
   * @return The style.
   */
  com.cg.sdui.components.image.v1.ImageStyle getStyle();
  /**
   * <code>.components.image.v1.ImageStyle style = 3 [json_name = "style"];</code>
   */
  com.cg.sdui.components.image.v1.ImageStyleOrBuilder getStyleOrBuilder();

  /**
   * <code>optional .components.properties.v1.Action action = 4 [json_name = "action"];</code>
   * @return Whether the action field is set.
   */
  boolean hasAction();
  /**
   * <code>optional .components.properties.v1.Action action = 4 [json_name = "action"];</code>
   * @return The action.
   */
  com.cg.sdui.components.properties.v1.Action getAction();
  /**
   * <code>optional .components.properties.v1.Action action = 4 [json_name = "action"];</code>
   */
  com.cg.sdui.components.properties.v1.ActionOrBuilder getActionOrBuilder();
}
