// Code generated by connect-kotlin. DO NOT EDIT.
//
// Source: grpc/v1/screen_service.proto
//
package com.cg.sdui.grpc.v1

import com.cg.sdui.screens.v1.SDUIScreen
import com.connectrpc.Headers
import com.connectrpc.ResponseMessage

public interface ScreenServiceClientInterface {
  public suspend fun getScreenUI(request: LayoutRequest, headers: Headers = emptyMap()): ResponseMessage<SDUIScreen>
}
