// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/grid/grid.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.cg.sdui.components.grid;

@kotlin.jvm.JvmName("-initializesDUIGrid")
public inline fun sDUIGrid(block: com.cg.sdui.components.grid.SDUIGridKt.Dsl.() -> kotlin.Unit): com.cg.sdui.components.grid.SDUIGrid =
  com.cg.sdui.components.grid.SDUIGridKt.Dsl._create(com.cg.sdui.components.grid.SDUIGrid.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `components.grid.SDUIGrid`
 */
public object SDUIGridKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.cg.sdui.components.grid.SDUIGrid.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.cg.sdui.components.grid.SDUIGrid.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.cg.sdui.components.grid.SDUIGrid = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class SduiComponentProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];`
     */
     public val sduiComponent: com.google.protobuf.kotlin.DslList<com.cg.sdui.components.properties.v1.SDUIComponent, SduiComponentProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.sduiComponentList
      )
    /**
     * `repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];`
     * @param value The sduiComponent to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addSduiComponent")
    public fun com.google.protobuf.kotlin.DslList<com.cg.sdui.components.properties.v1.SDUIComponent, SduiComponentProxy>.add(value: com.cg.sdui.components.properties.v1.SDUIComponent) {
      _builder.addSduiComponent(value)
    }
    /**
     * `repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];`
     * @param value The sduiComponent to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignSduiComponent")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.cg.sdui.components.properties.v1.SDUIComponent, SduiComponentProxy>.plusAssign(value: com.cg.sdui.components.properties.v1.SDUIComponent) {
      add(value)
    }
    /**
     * `repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];`
     * @param values The sduiComponent to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllSduiComponent")
    public fun com.google.protobuf.kotlin.DslList<com.cg.sdui.components.properties.v1.SDUIComponent, SduiComponentProxy>.addAll(values: kotlin.collections.Iterable<com.cg.sdui.components.properties.v1.SDUIComponent>) {
      _builder.addAllSduiComponent(values)
    }
    /**
     * `repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];`
     * @param values The sduiComponent to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllSduiComponent")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.cg.sdui.components.properties.v1.SDUIComponent, SduiComponentProxy>.plusAssign(values: kotlin.collections.Iterable<com.cg.sdui.components.properties.v1.SDUIComponent>) {
      addAll(values)
    }
    /**
     * `repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];`
     * @param index The index to set the value at.
     * @param value The sduiComponent to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setSduiComponent")
    public operator fun com.google.protobuf.kotlin.DslList<com.cg.sdui.components.properties.v1.SDUIComponent, SduiComponentProxy>.set(index: kotlin.Int, value: com.cg.sdui.components.properties.v1.SDUIComponent) {
      _builder.setSduiComponent(index, value)
    }
    /**
     * `repeated .components.properties.v1.SDUIComponent sdui_component = 1 [json_name = "sduiComponent"];`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearSduiComponent")
    public fun com.google.protobuf.kotlin.DslList<com.cg.sdui.components.properties.v1.SDUIComponent, SduiComponentProxy>.clear() {
      _builder.clearSduiComponent()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.cg.sdui.components.grid.SDUIGrid.copy(block: `com.cg.sdui.components.grid`.SDUIGridKt.Dsl.() -> kotlin.Unit): com.cg.sdui.components.grid.SDUIGrid =
  `com.cg.sdui.components.grid`.SDUIGridKt.Dsl._create(this.toBuilder()).apply { block() }._build()

