// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/menu/menu_item.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.components.menu;

/**
 * Protobuf type {@code components.menu.MenuItem}
 */
public final class MenuItem extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:components.menu.MenuItem)
    MenuItemOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      MenuItem.class.getName());
  }
  // Use MenuItem.newBuilder() to construct.
  private MenuItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private MenuItem() {
    title_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cg.sdui.components.menu.MenuItemProto.internal_static_components_menu_MenuItem_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cg.sdui.components.menu.MenuItemProto.internal_static_components_menu_MenuItem_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cg.sdui.components.menu.MenuItem.class, com.cg.sdui.components.menu.MenuItem.Builder.class);
  }

  private int bitField0_;
  public static final int LEADING_ICON_FIELD_NUMBER = 1;
  private com.cg.sdui.components.icon.v1.Icon leadingIcon_;
  /**
   * <code>.components.icon.v1.Icon leading_icon = 1 [json_name = "leadingIcon"];</code>
   * @return Whether the leadingIcon field is set.
   */
  @java.lang.Override
  public boolean hasLeadingIcon() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.components.icon.v1.Icon leading_icon = 1 [json_name = "leadingIcon"];</code>
   * @return The leadingIcon.
   */
  @java.lang.Override
  public com.cg.sdui.components.icon.v1.Icon getLeadingIcon() {
    return leadingIcon_ == null ? com.cg.sdui.components.icon.v1.Icon.getDefaultInstance() : leadingIcon_;
  }
  /**
   * <code>.components.icon.v1.Icon leading_icon = 1 [json_name = "leadingIcon"];</code>
   */
  @java.lang.Override
  public com.cg.sdui.components.icon.v1.IconOrBuilder getLeadingIconOrBuilder() {
    return leadingIcon_ == null ? com.cg.sdui.components.icon.v1.Icon.getDefaultInstance() : leadingIcon_;
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object title_ = "";
  /**
   * <code>string title = 2 [json_name = "title"];</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 2 [json_name = "title"];</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRAILING_ICON_FIELD_NUMBER = 3;
  private com.cg.sdui.components.icon.v1.Icon trailingIcon_;
  /**
   * <code>.components.icon.v1.Icon trailing_icon = 3 [json_name = "trailingIcon"];</code>
   * @return Whether the trailingIcon field is set.
   */
  @java.lang.Override
  public boolean hasTrailingIcon() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.components.icon.v1.Icon trailing_icon = 3 [json_name = "trailingIcon"];</code>
   * @return The trailingIcon.
   */
  @java.lang.Override
  public com.cg.sdui.components.icon.v1.Icon getTrailingIcon() {
    return trailingIcon_ == null ? com.cg.sdui.components.icon.v1.Icon.getDefaultInstance() : trailingIcon_;
  }
  /**
   * <code>.components.icon.v1.Icon trailing_icon = 3 [json_name = "trailingIcon"];</code>
   */
  @java.lang.Override
  public com.cg.sdui.components.icon.v1.IconOrBuilder getTrailingIconOrBuilder() {
    return trailingIcon_ == null ? com.cg.sdui.components.icon.v1.Icon.getDefaultInstance() : trailingIcon_;
  }

  public static final int ACTION_FIELD_NUMBER = 4;
  private com.cg.sdui.components.properties.v1.Action action_;
  /**
   * <code>.components.properties.v1.Action action = 4 [json_name = "action"];</code>
   * @return Whether the action field is set.
   */
  @java.lang.Override
  public boolean hasAction() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.components.properties.v1.Action action = 4 [json_name = "action"];</code>
   * @return The action.
   */
  @java.lang.Override
  public com.cg.sdui.components.properties.v1.Action getAction() {
    return action_ == null ? com.cg.sdui.components.properties.v1.Action.getDefaultInstance() : action_;
  }
  /**
   * <code>.components.properties.v1.Action action = 4 [json_name = "action"];</code>
   */
  @java.lang.Override
  public com.cg.sdui.components.properties.v1.ActionOrBuilder getActionOrBuilder() {
    return action_ == null ? com.cg.sdui.components.properties.v1.Action.getDefaultInstance() : action_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getLeadingIcon());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, title_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(3, getTrailingIcon());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(4, getAction());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLeadingIcon());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, title_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getTrailingIcon());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getAction());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cg.sdui.components.menu.MenuItem)) {
      return super.equals(obj);
    }
    com.cg.sdui.components.menu.MenuItem other = (com.cg.sdui.components.menu.MenuItem) obj;

    if (hasLeadingIcon() != other.hasLeadingIcon()) return false;
    if (hasLeadingIcon()) {
      if (!getLeadingIcon()
          .equals(other.getLeadingIcon())) return false;
    }
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (hasTrailingIcon() != other.hasTrailingIcon()) return false;
    if (hasTrailingIcon()) {
      if (!getTrailingIcon()
          .equals(other.getTrailingIcon())) return false;
    }
    if (hasAction() != other.hasAction()) return false;
    if (hasAction()) {
      if (!getAction()
          .equals(other.getAction())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLeadingIcon()) {
      hash = (37 * hash) + LEADING_ICON_FIELD_NUMBER;
      hash = (53 * hash) + getLeadingIcon().hashCode();
    }
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    if (hasTrailingIcon()) {
      hash = (37 * hash) + TRAILING_ICON_FIELD_NUMBER;
      hash = (53 * hash) + getTrailingIcon().hashCode();
    }
    if (hasAction()) {
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cg.sdui.components.menu.MenuItem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.sdui.components.menu.MenuItem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.sdui.components.menu.MenuItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.sdui.components.menu.MenuItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.sdui.components.menu.MenuItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.sdui.components.menu.MenuItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.sdui.components.menu.MenuItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cg.sdui.components.menu.MenuItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.cg.sdui.components.menu.MenuItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.cg.sdui.components.menu.MenuItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cg.sdui.components.menu.MenuItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cg.sdui.components.menu.MenuItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cg.sdui.components.menu.MenuItem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code components.menu.MenuItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:components.menu.MenuItem)
      com.cg.sdui.components.menu.MenuItemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cg.sdui.components.menu.MenuItemProto.internal_static_components_menu_MenuItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cg.sdui.components.menu.MenuItemProto.internal_static_components_menu_MenuItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cg.sdui.components.menu.MenuItem.class, com.cg.sdui.components.menu.MenuItem.Builder.class);
    }

    // Construct using com.cg.sdui.components.menu.MenuItem.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getLeadingIconFieldBuilder();
        getTrailingIconFieldBuilder();
        getActionFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      leadingIcon_ = null;
      if (leadingIconBuilder_ != null) {
        leadingIconBuilder_.dispose();
        leadingIconBuilder_ = null;
      }
      title_ = "";
      trailingIcon_ = null;
      if (trailingIconBuilder_ != null) {
        trailingIconBuilder_.dispose();
        trailingIconBuilder_ = null;
      }
      action_ = null;
      if (actionBuilder_ != null) {
        actionBuilder_.dispose();
        actionBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cg.sdui.components.menu.MenuItemProto.internal_static_components_menu_MenuItem_descriptor;
    }

    @java.lang.Override
    public com.cg.sdui.components.menu.MenuItem getDefaultInstanceForType() {
      return com.cg.sdui.components.menu.MenuItem.getDefaultInstance();
    }

    @java.lang.Override
    public com.cg.sdui.components.menu.MenuItem build() {
      com.cg.sdui.components.menu.MenuItem result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cg.sdui.components.menu.MenuItem buildPartial() {
      com.cg.sdui.components.menu.MenuItem result = new com.cg.sdui.components.menu.MenuItem(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.cg.sdui.components.menu.MenuItem result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.leadingIcon_ = leadingIconBuilder_ == null
            ? leadingIcon_
            : leadingIconBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.title_ = title_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.trailingIcon_ = trailingIconBuilder_ == null
            ? trailingIcon_
            : trailingIconBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.action_ = actionBuilder_ == null
            ? action_
            : actionBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cg.sdui.components.menu.MenuItem) {
        return mergeFrom((com.cg.sdui.components.menu.MenuItem)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cg.sdui.components.menu.MenuItem other) {
      if (other == com.cg.sdui.components.menu.MenuItem.getDefaultInstance()) return this;
      if (other.hasLeadingIcon()) {
        mergeLeadingIcon(other.getLeadingIcon());
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasTrailingIcon()) {
        mergeTrailingIcon(other.getTrailingIcon());
      }
      if (other.hasAction()) {
        mergeAction(other.getAction());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getLeadingIconFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              title_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getTrailingIconFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getActionFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.cg.sdui.components.icon.v1.Icon leadingIcon_;
    private com.google.protobuf.SingleFieldBuilder<
        com.cg.sdui.components.icon.v1.Icon, com.cg.sdui.components.icon.v1.Icon.Builder, com.cg.sdui.components.icon.v1.IconOrBuilder> leadingIconBuilder_;
    /**
     * <code>.components.icon.v1.Icon leading_icon = 1 [json_name = "leadingIcon"];</code>
     * @return Whether the leadingIcon field is set.
     */
    public boolean hasLeadingIcon() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.components.icon.v1.Icon leading_icon = 1 [json_name = "leadingIcon"];</code>
     * @return The leadingIcon.
     */
    public com.cg.sdui.components.icon.v1.Icon getLeadingIcon() {
      if (leadingIconBuilder_ == null) {
        return leadingIcon_ == null ? com.cg.sdui.components.icon.v1.Icon.getDefaultInstance() : leadingIcon_;
      } else {
        return leadingIconBuilder_.getMessage();
      }
    }
    /**
     * <code>.components.icon.v1.Icon leading_icon = 1 [json_name = "leadingIcon"];</code>
     */
    public Builder setLeadingIcon(com.cg.sdui.components.icon.v1.Icon value) {
      if (leadingIconBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        leadingIcon_ = value;
      } else {
        leadingIconBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.components.icon.v1.Icon leading_icon = 1 [json_name = "leadingIcon"];</code>
     */
    public Builder setLeadingIcon(
        com.cg.sdui.components.icon.v1.Icon.Builder builderForValue) {
      if (leadingIconBuilder_ == null) {
        leadingIcon_ = builderForValue.build();
      } else {
        leadingIconBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.components.icon.v1.Icon leading_icon = 1 [json_name = "leadingIcon"];</code>
     */
    public Builder mergeLeadingIcon(com.cg.sdui.components.icon.v1.Icon value) {
      if (leadingIconBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          leadingIcon_ != null &&
          leadingIcon_ != com.cg.sdui.components.icon.v1.Icon.getDefaultInstance()) {
          getLeadingIconBuilder().mergeFrom(value);
        } else {
          leadingIcon_ = value;
        }
      } else {
        leadingIconBuilder_.mergeFrom(value);
      }
      if (leadingIcon_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.components.icon.v1.Icon leading_icon = 1 [json_name = "leadingIcon"];</code>
     */
    public Builder clearLeadingIcon() {
      bitField0_ = (bitField0_ & ~0x00000001);
      leadingIcon_ = null;
      if (leadingIconBuilder_ != null) {
        leadingIconBuilder_.dispose();
        leadingIconBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.components.icon.v1.Icon leading_icon = 1 [json_name = "leadingIcon"];</code>
     */
    public com.cg.sdui.components.icon.v1.Icon.Builder getLeadingIconBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getLeadingIconFieldBuilder().getBuilder();
    }
    /**
     * <code>.components.icon.v1.Icon leading_icon = 1 [json_name = "leadingIcon"];</code>
     */
    public com.cg.sdui.components.icon.v1.IconOrBuilder getLeadingIconOrBuilder() {
      if (leadingIconBuilder_ != null) {
        return leadingIconBuilder_.getMessageOrBuilder();
      } else {
        return leadingIcon_ == null ?
            com.cg.sdui.components.icon.v1.Icon.getDefaultInstance() : leadingIcon_;
      }
    }
    /**
     * <code>.components.icon.v1.Icon leading_icon = 1 [json_name = "leadingIcon"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.cg.sdui.components.icon.v1.Icon, com.cg.sdui.components.icon.v1.Icon.Builder, com.cg.sdui.components.icon.v1.IconOrBuilder> 
        getLeadingIconFieldBuilder() {
      if (leadingIconBuilder_ == null) {
        leadingIconBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.cg.sdui.components.icon.v1.Icon, com.cg.sdui.components.icon.v1.Icon.Builder, com.cg.sdui.components.icon.v1.IconOrBuilder>(
                getLeadingIcon(),
                getParentForChildren(),
                isClean());
        leadingIcon_ = null;
      }
      return leadingIconBuilder_;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 2 [json_name = "title"];</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 2 [json_name = "title"];</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 2 [json_name = "title"];</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      title_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2 [json_name = "title"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2 [json_name = "title"];</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private com.cg.sdui.components.icon.v1.Icon trailingIcon_;
    private com.google.protobuf.SingleFieldBuilder<
        com.cg.sdui.components.icon.v1.Icon, com.cg.sdui.components.icon.v1.Icon.Builder, com.cg.sdui.components.icon.v1.IconOrBuilder> trailingIconBuilder_;
    /**
     * <code>.components.icon.v1.Icon trailing_icon = 3 [json_name = "trailingIcon"];</code>
     * @return Whether the trailingIcon field is set.
     */
    public boolean hasTrailingIcon() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.components.icon.v1.Icon trailing_icon = 3 [json_name = "trailingIcon"];</code>
     * @return The trailingIcon.
     */
    public com.cg.sdui.components.icon.v1.Icon getTrailingIcon() {
      if (trailingIconBuilder_ == null) {
        return trailingIcon_ == null ? com.cg.sdui.components.icon.v1.Icon.getDefaultInstance() : trailingIcon_;
      } else {
        return trailingIconBuilder_.getMessage();
      }
    }
    /**
     * <code>.components.icon.v1.Icon trailing_icon = 3 [json_name = "trailingIcon"];</code>
     */
    public Builder setTrailingIcon(com.cg.sdui.components.icon.v1.Icon value) {
      if (trailingIconBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        trailingIcon_ = value;
      } else {
        trailingIconBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.components.icon.v1.Icon trailing_icon = 3 [json_name = "trailingIcon"];</code>
     */
    public Builder setTrailingIcon(
        com.cg.sdui.components.icon.v1.Icon.Builder builderForValue) {
      if (trailingIconBuilder_ == null) {
        trailingIcon_ = builderForValue.build();
      } else {
        trailingIconBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.components.icon.v1.Icon trailing_icon = 3 [json_name = "trailingIcon"];</code>
     */
    public Builder mergeTrailingIcon(com.cg.sdui.components.icon.v1.Icon value) {
      if (trailingIconBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          trailingIcon_ != null &&
          trailingIcon_ != com.cg.sdui.components.icon.v1.Icon.getDefaultInstance()) {
          getTrailingIconBuilder().mergeFrom(value);
        } else {
          trailingIcon_ = value;
        }
      } else {
        trailingIconBuilder_.mergeFrom(value);
      }
      if (trailingIcon_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.components.icon.v1.Icon trailing_icon = 3 [json_name = "trailingIcon"];</code>
     */
    public Builder clearTrailingIcon() {
      bitField0_ = (bitField0_ & ~0x00000004);
      trailingIcon_ = null;
      if (trailingIconBuilder_ != null) {
        trailingIconBuilder_.dispose();
        trailingIconBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.components.icon.v1.Icon trailing_icon = 3 [json_name = "trailingIcon"];</code>
     */
    public com.cg.sdui.components.icon.v1.Icon.Builder getTrailingIconBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getTrailingIconFieldBuilder().getBuilder();
    }
    /**
     * <code>.components.icon.v1.Icon trailing_icon = 3 [json_name = "trailingIcon"];</code>
     */
    public com.cg.sdui.components.icon.v1.IconOrBuilder getTrailingIconOrBuilder() {
      if (trailingIconBuilder_ != null) {
        return trailingIconBuilder_.getMessageOrBuilder();
      } else {
        return trailingIcon_ == null ?
            com.cg.sdui.components.icon.v1.Icon.getDefaultInstance() : trailingIcon_;
      }
    }
    /**
     * <code>.components.icon.v1.Icon trailing_icon = 3 [json_name = "trailingIcon"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.cg.sdui.components.icon.v1.Icon, com.cg.sdui.components.icon.v1.Icon.Builder, com.cg.sdui.components.icon.v1.IconOrBuilder> 
        getTrailingIconFieldBuilder() {
      if (trailingIconBuilder_ == null) {
        trailingIconBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.cg.sdui.components.icon.v1.Icon, com.cg.sdui.components.icon.v1.Icon.Builder, com.cg.sdui.components.icon.v1.IconOrBuilder>(
                getTrailingIcon(),
                getParentForChildren(),
                isClean());
        trailingIcon_ = null;
      }
      return trailingIconBuilder_;
    }

    private com.cg.sdui.components.properties.v1.Action action_;
    private com.google.protobuf.SingleFieldBuilder<
        com.cg.sdui.components.properties.v1.Action, com.cg.sdui.components.properties.v1.Action.Builder, com.cg.sdui.components.properties.v1.ActionOrBuilder> actionBuilder_;
    /**
     * <code>.components.properties.v1.Action action = 4 [json_name = "action"];</code>
     * @return Whether the action field is set.
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.components.properties.v1.Action action = 4 [json_name = "action"];</code>
     * @return The action.
     */
    public com.cg.sdui.components.properties.v1.Action getAction() {
      if (actionBuilder_ == null) {
        return action_ == null ? com.cg.sdui.components.properties.v1.Action.getDefaultInstance() : action_;
      } else {
        return actionBuilder_.getMessage();
      }
    }
    /**
     * <code>.components.properties.v1.Action action = 4 [json_name = "action"];</code>
     */
    public Builder setAction(com.cg.sdui.components.properties.v1.Action value) {
      if (actionBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        action_ = value;
      } else {
        actionBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.components.properties.v1.Action action = 4 [json_name = "action"];</code>
     */
    public Builder setAction(
        com.cg.sdui.components.properties.v1.Action.Builder builderForValue) {
      if (actionBuilder_ == null) {
        action_ = builderForValue.build();
      } else {
        actionBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.components.properties.v1.Action action = 4 [json_name = "action"];</code>
     */
    public Builder mergeAction(com.cg.sdui.components.properties.v1.Action value) {
      if (actionBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          action_ != null &&
          action_ != com.cg.sdui.components.properties.v1.Action.getDefaultInstance()) {
          getActionBuilder().mergeFrom(value);
        } else {
          action_ = value;
        }
      } else {
        actionBuilder_.mergeFrom(value);
      }
      if (action_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.components.properties.v1.Action action = 4 [json_name = "action"];</code>
     */
    public Builder clearAction() {
      bitField0_ = (bitField0_ & ~0x00000008);
      action_ = null;
      if (actionBuilder_ != null) {
        actionBuilder_.dispose();
        actionBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.components.properties.v1.Action action = 4 [json_name = "action"];</code>
     */
    public com.cg.sdui.components.properties.v1.Action.Builder getActionBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getActionFieldBuilder().getBuilder();
    }
    /**
     * <code>.components.properties.v1.Action action = 4 [json_name = "action"];</code>
     */
    public com.cg.sdui.components.properties.v1.ActionOrBuilder getActionOrBuilder() {
      if (actionBuilder_ != null) {
        return actionBuilder_.getMessageOrBuilder();
      } else {
        return action_ == null ?
            com.cg.sdui.components.properties.v1.Action.getDefaultInstance() : action_;
      }
    }
    /**
     * <code>.components.properties.v1.Action action = 4 [json_name = "action"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.cg.sdui.components.properties.v1.Action, com.cg.sdui.components.properties.v1.Action.Builder, com.cg.sdui.components.properties.v1.ActionOrBuilder> 
        getActionFieldBuilder() {
      if (actionBuilder_ == null) {
        actionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.cg.sdui.components.properties.v1.Action, com.cg.sdui.components.properties.v1.Action.Builder, com.cg.sdui.components.properties.v1.ActionOrBuilder>(
                getAction(),
                getParentForChildren(),
                isClean());
        action_ = null;
      }
      return actionBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:components.menu.MenuItem)
  }

  // @@protoc_insertion_point(class_scope:components.menu.MenuItem)
  private static final com.cg.sdui.components.menu.MenuItem DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cg.sdui.components.menu.MenuItem();
  }

  public static com.cg.sdui.components.menu.MenuItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MenuItem>
      PARSER = new com.google.protobuf.AbstractParser<MenuItem>() {
    @java.lang.Override
    public MenuItem parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MenuItem> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MenuItem> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cg.sdui.components.menu.MenuItem getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

