// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/menu/menu_item.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.components.menu;

public final class MenuItemProto {
  private MenuItemProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      MenuItemProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_components_menu_MenuItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_components_menu_MenuItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037components/menu/menu_item.proto\022\017compo" +
      "nents.menu\032%components/properties/v1/act" +
      "ion.proto\032-components/properties/v1/text" +
      "_alignment.proto\032\035components/icon/v1/ico" +
      "n.proto\"\326\001\n\010MenuItem\022;\n\014leading_icon\030\001 \001" +
      "(\0132\030.components.icon.v1.IconR\013leadingIco" +
      "n\022\024\n\005title\030\002 \001(\tR\005title\022=\n\rtrailing_icon" +
      "\030\003 \001(\0132\030.components.icon.v1.IconR\014traili" +
      "ngIcon\0228\n\006action\030\004 \001(\0132 .components.prop" +
      "erties.v1.ActionR\006actionB\211\001\n\033com.cg.sdui" +
      ".components.menuB\rMenuItemProtoP\001\242\002\003CMX\252" +
      "\002\017Components.Menu\312\002\017Components\\Menu\342\002\033Co" +
      "mponents\\Menu\\GPBMetadata\352\002\020Components::" +
      "Menub\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.cg.sdui.components.properties.v1.ActionProto.getDescriptor(),
          com.cg.sdui.components.properties.v1.TextAlignmentProto.getDescriptor(),
          com.cg.sdui.components.icon.v1.IconProto.getDescriptor(),
        });
    internal_static_components_menu_MenuItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_components_menu_MenuItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_components_menu_MenuItem_descriptor,
        new java.lang.String[] { "LeadingIcon", "Title", "TrailingIcon", "Action", });
    descriptor.resolveAllFeaturesImmutable();
    com.cg.sdui.components.properties.v1.ActionProto.getDescriptor();
    com.cg.sdui.components.properties.v1.TextAlignmentProto.getDescriptor();
    com.cg.sdui.components.icon.v1.IconProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
