// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: grpc/v1/screen_service.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.grpc.v1;

public interface LayoutRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.v1.LayoutRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1 [json_name = "type"];</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 1 [json_name = "type"];</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
