// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: grpc/v1/screen_service.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.grpc.v1;

public final class ScreenServiceProto {
  private ScreenServiceProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      ScreenServiceProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_v1_LayoutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_v1_LayoutRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034grpc/v1/screen_service.proto\022\007grpc.v1\032" +
      "\032screens/v1/screen_ui.proto\"#\n\rLayoutReq" +
      "uest\022\022\n\004type\030\001 \001(\tR\004type2P\n\rScreenServic" +
      "e\022?\n\013getScreenUI\022\026.grpc.v1.LayoutRequest" +
      "\032\026.screens.v1.SDUIScreen\"\000Bf\n\023com.cg.sdu" +
      "i.grpc.v1B\022ScreenServiceProtoP\001\242\002\003GXX\252\002\007" +
      "Grpc.V1\312\002\007Grpc\\V1\342\002\023Grpc\\V1\\GPBMetadata\352" +
      "\002\010Grpc::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.cg.sdui.screens.v1.ScreenUiProto.getDescriptor(),
        });
    internal_static_grpc_v1_LayoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_v1_LayoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_v1_LayoutRequest_descriptor,
        new java.lang.String[] { "Type", });
    descriptor.resolveAllFeaturesImmutable();
    com.cg.sdui.screens.v1.ScreenUiProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
