// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/button/v1/button.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.cg.sdui.components.button.v1;

@kotlin.jvm.JvmName("-initializebuttonStyle")
public inline fun buttonStyle(block: com.cg.sdui.components.button.v1.ButtonStyleKt.Dsl.() -> kotlin.Unit): com.cg.sdui.components.button.v1.ButtonStyle =
  com.cg.sdui.components.button.v1.ButtonStyleKt.Dsl._create(com.cg.sdui.components.button.v1.ButtonStyle.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `components.button.v1.ButtonStyle`
 */
public object ButtonStyleKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.cg.sdui.components.button.v1.ButtonStyle.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.cg.sdui.components.button.v1.ButtonStyle.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.cg.sdui.components.button.v1.ButtonStyle = _builder.build()

    /**
     * `bool fullWidth = 1 [json_name = "fullWidth"];`
     */
    public var fullWidth: kotlin.Boolean
      @kotlin.jvm.JvmName("getFullWidth")
        get() = _builder.fullWidth
      @kotlin.jvm.JvmName("setFullWidth")
        set(value) {
        _builder.fullWidth = value
      }
    /**
     * `bool fullWidth = 1 [json_name = "fullWidth"];`
     */
    public fun clearFullWidth() {
      _builder.clearFullWidth()
    }

    /**
     * `string backgroundColor = 2 [json_name = "backgroundColor"];`
     */
    public var backgroundColor: kotlin.String
      @kotlin.jvm.JvmName("getBackgroundColor")
        get() = _builder.backgroundColor
      @kotlin.jvm.JvmName("setBackgroundColor")
        set(value) {
        _builder.backgroundColor = value
      }
    /**
     * `string backgroundColor = 2 [json_name = "backgroundColor"];`
     */
    public fun clearBackgroundColor() {
      _builder.clearBackgroundColor()
    }

    /**
     * `string txtColor = 3 [json_name = "txtColor"];`
     */
    public var txtColor: kotlin.String
      @kotlin.jvm.JvmName("getTxtColor")
        get() = _builder.txtColor
      @kotlin.jvm.JvmName("setTxtColor")
        set(value) {
        _builder.txtColor = value
      }
    /**
     * `string txtColor = 3 [json_name = "txtColor"];`
     */
    public fun clearTxtColor() {
      _builder.clearTxtColor()
    }

    /**
     * `.components.properties.v1.TextAlignment textAlignment = 4 [json_name = "textAlignment"];`
     */
    public var textAlignment: com.cg.sdui.components.properties.v1.TextAlignment
      @kotlin.jvm.JvmName("getTextAlignment")
        get() = _builder.textAlignment
      @kotlin.jvm.JvmName("setTextAlignment")
        set(value) {
        _builder.textAlignment = value
      }
    public var textAlignmentValue: kotlin.Int
      @kotlin.jvm.JvmName("getTextAlignmentValue")
        get() = _builder.textAlignmentValue
      @kotlin.jvm.JvmName("setTextAlignmentValue")
        set(value) {
        _builder.textAlignmentValue = value
      }
    /**
     * `.components.properties.v1.TextAlignment textAlignment = 4 [json_name = "textAlignment"];`
     */
    public fun clearTextAlignment() {
      _builder.clearTextAlignment()
    }

    /**
     * `.components.icon.v1.Icon leadingIcon = 5 [json_name = "leadingIcon"];`
     */
    public var leadingIcon: com.cg.sdui.components.icon.v1.Icon
      @kotlin.jvm.JvmName("getLeadingIcon")
        get() = _builder.leadingIcon
      @kotlin.jvm.JvmName("setLeadingIcon")
        set(value) {
        _builder.leadingIcon = value
      }
    /**
     * `.components.icon.v1.Icon leadingIcon = 5 [json_name = "leadingIcon"];`
     */
    public fun clearLeadingIcon() {
      _builder.clearLeadingIcon()
    }
    /**
     * `.components.icon.v1.Icon leadingIcon = 5 [json_name = "leadingIcon"];`
     * @return Whether the leadingIcon field is set.
     */
    public fun hasLeadingIcon(): kotlin.Boolean {
      return _builder.hasLeadingIcon()
    }

    public val ButtonStyleKt.Dsl.leadingIconOrNull: com.cg.sdui.components.icon.v1.Icon?
      get() = _builder.leadingIconOrNull

    /**
     * `.components.icon.v1.Icon trailingIcon = 6 [json_name = "trailingIcon"];`
     */
    public var trailingIcon: com.cg.sdui.components.icon.v1.Icon
      @kotlin.jvm.JvmName("getTrailingIcon")
        get() = _builder.trailingIcon
      @kotlin.jvm.JvmName("setTrailingIcon")
        set(value) {
        _builder.trailingIcon = value
      }
    /**
     * `.components.icon.v1.Icon trailingIcon = 6 [json_name = "trailingIcon"];`
     */
    public fun clearTrailingIcon() {
      _builder.clearTrailingIcon()
    }
    /**
     * `.components.icon.v1.Icon trailingIcon = 6 [json_name = "trailingIcon"];`
     * @return Whether the trailingIcon field is set.
     */
    public fun hasTrailingIcon(): kotlin.Boolean {
      return _builder.hasTrailingIcon()
    }

    public val ButtonStyleKt.Dsl.trailingIconOrNull: com.cg.sdui.components.icon.v1.Icon?
      get() = _builder.trailingIconOrNull

    /**
     * `optional .components.properties.v1.Shape shape = 7 [json_name = "shape"];`
     */
    public var shape: com.cg.sdui.components.properties.v1.Shape
      @kotlin.jvm.JvmName("getShape")
        get() = _builder.shape
      @kotlin.jvm.JvmName("setShape")
        set(value) {
        _builder.shape = value
      }
    /**
     * `optional .components.properties.v1.Shape shape = 7 [json_name = "shape"];`
     */
    public fun clearShape() {
      _builder.clearShape()
    }
    /**
     * `optional .components.properties.v1.Shape shape = 7 [json_name = "shape"];`
     * @return Whether the shape field is set.
     */
    public fun hasShape(): kotlin.Boolean {
      return _builder.hasShape()
    }

    public val ButtonStyleKt.Dsl.shapeOrNull: com.cg.sdui.components.properties.v1.Shape?
      get() = _builder.shapeOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.cg.sdui.components.button.v1.ButtonStyle.copy(block: `com.cg.sdui.components.button.v1`.ButtonStyleKt.Dsl.() -> kotlin.Unit): com.cg.sdui.components.button.v1.ButtonStyle =
  `com.cg.sdui.components.button.v1`.ButtonStyleKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.cg.sdui.components.button.v1.ButtonStyleOrBuilder.leadingIconOrNull: com.cg.sdui.components.icon.v1.Icon?
  get() = if (hasLeadingIcon()) getLeadingIcon() else null

public val com.cg.sdui.components.button.v1.ButtonStyleOrBuilder.trailingIconOrNull: com.cg.sdui.components.icon.v1.Icon?
  get() = if (hasTrailingIcon()) getTrailingIcon() else null

public val com.cg.sdui.components.button.v1.ButtonStyleOrBuilder.shapeOrNull: com.cg.sdui.components.properties.v1.Shape?
  get() = if (hasShape()) getShape() else null

