// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/cards/offer_card.proto
// Protobuf Java Version: 4.27.2

package com.cg.sdui.components.cards;

/**
 * Protobuf type {@code components.cards.OfferCard}
 */
public final class OfferCard extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:components.cards.OfferCard)
    OfferCardOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      OfferCard.class.getName());
  }
  // Use OfferCard.newBuilder() to construct.
  private OfferCard(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private OfferCard() {
    backgroundColor_ = "";
    header_ = "";
    subTitle_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cg.sdui.components.cards.OfferCardProto.internal_static_components_cards_OfferCard_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cg.sdui.components.cards.OfferCardProto.internal_static_components_cards_OfferCard_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cg.sdui.components.cards.OfferCard.class, com.cg.sdui.components.cards.OfferCard.Builder.class);
  }

  private int bitField0_;
  public static final int IMAGE_FIELD_NUMBER = 1;
  private com.cg.sdui.components.image.v1.SDUIImageView image_;
  /**
   * <code>optional .components.image.v1.SDUIImageView image = 1 [json_name = "image"];</code>
   * @return Whether the image field is set.
   */
  @java.lang.Override
  public boolean hasImage() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .components.image.v1.SDUIImageView image = 1 [json_name = "image"];</code>
   * @return The image.
   */
  @java.lang.Override
  public com.cg.sdui.components.image.v1.SDUIImageView getImage() {
    return image_ == null ? com.cg.sdui.components.image.v1.SDUIImageView.getDefaultInstance() : image_;
  }
  /**
   * <code>optional .components.image.v1.SDUIImageView image = 1 [json_name = "image"];</code>
   */
  @java.lang.Override
  public com.cg.sdui.components.image.v1.SDUIImageViewOrBuilder getImageOrBuilder() {
    return image_ == null ? com.cg.sdui.components.image.v1.SDUIImageView.getDefaultInstance() : image_;
  }

  public static final int BACKGROUND_COLOR_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object backgroundColor_ = "";
  /**
   * <code>optional string background_color = 2 [json_name = "backgroundColor"];</code>
   * @return Whether the backgroundColor field is set.
   */
  @java.lang.Override
  public boolean hasBackgroundColor() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional string background_color = 2 [json_name = "backgroundColor"];</code>
   * @return The backgroundColor.
   */
  @java.lang.Override
  public java.lang.String getBackgroundColor() {
    java.lang.Object ref = backgroundColor_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      backgroundColor_ = s;
      return s;
    }
  }
  /**
   * <code>optional string background_color = 2 [json_name = "backgroundColor"];</code>
   * @return The bytes for backgroundColor.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBackgroundColorBytes() {
    java.lang.Object ref = backgroundColor_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      backgroundColor_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HEADER_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object header_ = "";
  /**
   * <code>optional string header = 3 [json_name = "header"];</code>
   * @return Whether the header field is set.
   */
  @java.lang.Override
  public boolean hasHeader() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional string header = 3 [json_name = "header"];</code>
   * @return The header.
   */
  @java.lang.Override
  public java.lang.String getHeader() {
    java.lang.Object ref = header_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      header_ = s;
      return s;
    }
  }
  /**
   * <code>optional string header = 3 [json_name = "header"];</code>
   * @return The bytes for header.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getHeaderBytes() {
    java.lang.Object ref = header_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      header_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUB_TITLE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object subTitle_ = "";
  /**
   * <code>optional string sub_title = 4 [json_name = "subTitle"];</code>
   * @return Whether the subTitle field is set.
   */
  @java.lang.Override
  public boolean hasSubTitle() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional string sub_title = 4 [json_name = "subTitle"];</code>
   * @return The subTitle.
   */
  @java.lang.Override
  public java.lang.String getSubTitle() {
    java.lang.Object ref = subTitle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      subTitle_ = s;
      return s;
    }
  }
  /**
   * <code>optional string sub_title = 4 [json_name = "subTitle"];</code>
   * @return The bytes for subTitle.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSubTitleBytes() {
    java.lang.Object ref = subTitle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      subTitle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BUTTON_FIELD_NUMBER = 5;
  private com.cg.sdui.components.button.v1.SDUIButton button_;
  /**
   * <code>optional .components.button.v1.SDUIButton button = 5 [json_name = "button"];</code>
   * @return Whether the button field is set.
   */
  @java.lang.Override
  public boolean hasButton() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional .components.button.v1.SDUIButton button = 5 [json_name = "button"];</code>
   * @return The button.
   */
  @java.lang.Override
  public com.cg.sdui.components.button.v1.SDUIButton getButton() {
    return button_ == null ? com.cg.sdui.components.button.v1.SDUIButton.getDefaultInstance() : button_;
  }
  /**
   * <code>optional .components.button.v1.SDUIButton button = 5 [json_name = "button"];</code>
   */
  @java.lang.Override
  public com.cg.sdui.components.button.v1.SDUIButtonOrBuilder getButtonOrBuilder() {
    return button_ == null ? com.cg.sdui.components.button.v1.SDUIButton.getDefaultInstance() : button_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getImage());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, backgroundColor_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, header_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, subTitle_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(5, getButton());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getImage());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, backgroundColor_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, header_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, subTitle_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getButton());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cg.sdui.components.cards.OfferCard)) {
      return super.equals(obj);
    }
    com.cg.sdui.components.cards.OfferCard other = (com.cg.sdui.components.cards.OfferCard) obj;

    if (hasImage() != other.hasImage()) return false;
    if (hasImage()) {
      if (!getImage()
          .equals(other.getImage())) return false;
    }
    if (hasBackgroundColor() != other.hasBackgroundColor()) return false;
    if (hasBackgroundColor()) {
      if (!getBackgroundColor()
          .equals(other.getBackgroundColor())) return false;
    }
    if (hasHeader() != other.hasHeader()) return false;
    if (hasHeader()) {
      if (!getHeader()
          .equals(other.getHeader())) return false;
    }
    if (hasSubTitle() != other.hasSubTitle()) return false;
    if (hasSubTitle()) {
      if (!getSubTitle()
          .equals(other.getSubTitle())) return false;
    }
    if (hasButton() != other.hasButton()) return false;
    if (hasButton()) {
      if (!getButton()
          .equals(other.getButton())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasImage()) {
      hash = (37 * hash) + IMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getImage().hashCode();
    }
    if (hasBackgroundColor()) {
      hash = (37 * hash) + BACKGROUND_COLOR_FIELD_NUMBER;
      hash = (53 * hash) + getBackgroundColor().hashCode();
    }
    if (hasHeader()) {
      hash = (37 * hash) + HEADER_FIELD_NUMBER;
      hash = (53 * hash) + getHeader().hashCode();
    }
    if (hasSubTitle()) {
      hash = (37 * hash) + SUB_TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getSubTitle().hashCode();
    }
    if (hasButton()) {
      hash = (37 * hash) + BUTTON_FIELD_NUMBER;
      hash = (53 * hash) + getButton().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cg.sdui.components.cards.OfferCard parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.sdui.components.cards.OfferCard parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.sdui.components.cards.OfferCard parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.sdui.components.cards.OfferCard parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.sdui.components.cards.OfferCard parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.sdui.components.cards.OfferCard parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.sdui.components.cards.OfferCard parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cg.sdui.components.cards.OfferCard parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.cg.sdui.components.cards.OfferCard parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.cg.sdui.components.cards.OfferCard parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cg.sdui.components.cards.OfferCard parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.cg.sdui.components.cards.OfferCard parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cg.sdui.components.cards.OfferCard prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code components.cards.OfferCard}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:components.cards.OfferCard)
      com.cg.sdui.components.cards.OfferCardOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cg.sdui.components.cards.OfferCardProto.internal_static_components_cards_OfferCard_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cg.sdui.components.cards.OfferCardProto.internal_static_components_cards_OfferCard_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cg.sdui.components.cards.OfferCard.class, com.cg.sdui.components.cards.OfferCard.Builder.class);
    }

    // Construct using com.cg.sdui.components.cards.OfferCard.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getImageFieldBuilder();
        getButtonFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      image_ = null;
      if (imageBuilder_ != null) {
        imageBuilder_.dispose();
        imageBuilder_ = null;
      }
      backgroundColor_ = "";
      header_ = "";
      subTitle_ = "";
      button_ = null;
      if (buttonBuilder_ != null) {
        buttonBuilder_.dispose();
        buttonBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cg.sdui.components.cards.OfferCardProto.internal_static_components_cards_OfferCard_descriptor;
    }

    @java.lang.Override
    public com.cg.sdui.components.cards.OfferCard getDefaultInstanceForType() {
      return com.cg.sdui.components.cards.OfferCard.getDefaultInstance();
    }

    @java.lang.Override
    public com.cg.sdui.components.cards.OfferCard build() {
      com.cg.sdui.components.cards.OfferCard result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.cg.sdui.components.cards.OfferCard buildPartial() {
      com.cg.sdui.components.cards.OfferCard result = new com.cg.sdui.components.cards.OfferCard(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.cg.sdui.components.cards.OfferCard result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.image_ = imageBuilder_ == null
            ? image_
            : imageBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.backgroundColor_ = backgroundColor_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.header_ = header_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.subTitle_ = subTitle_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.button_ = buttonBuilder_ == null
            ? button_
            : buttonBuilder_.build();
        to_bitField0_ |= 0x00000010;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cg.sdui.components.cards.OfferCard) {
        return mergeFrom((com.cg.sdui.components.cards.OfferCard)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cg.sdui.components.cards.OfferCard other) {
      if (other == com.cg.sdui.components.cards.OfferCard.getDefaultInstance()) return this;
      if (other.hasImage()) {
        mergeImage(other.getImage());
      }
      if (other.hasBackgroundColor()) {
        backgroundColor_ = other.backgroundColor_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasHeader()) {
        header_ = other.header_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasSubTitle()) {
        subTitle_ = other.subTitle_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.hasButton()) {
        mergeButton(other.getButton());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getImageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              backgroundColor_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              header_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              subTitle_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getButtonFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.cg.sdui.components.image.v1.SDUIImageView image_;
    private com.google.protobuf.SingleFieldBuilder<
        com.cg.sdui.components.image.v1.SDUIImageView, com.cg.sdui.components.image.v1.SDUIImageView.Builder, com.cg.sdui.components.image.v1.SDUIImageViewOrBuilder> imageBuilder_;
    /**
     * <code>optional .components.image.v1.SDUIImageView image = 1 [json_name = "image"];</code>
     * @return Whether the image field is set.
     */
    public boolean hasImage() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .components.image.v1.SDUIImageView image = 1 [json_name = "image"];</code>
     * @return The image.
     */
    public com.cg.sdui.components.image.v1.SDUIImageView getImage() {
      if (imageBuilder_ == null) {
        return image_ == null ? com.cg.sdui.components.image.v1.SDUIImageView.getDefaultInstance() : image_;
      } else {
        return imageBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .components.image.v1.SDUIImageView image = 1 [json_name = "image"];</code>
     */
    public Builder setImage(com.cg.sdui.components.image.v1.SDUIImageView value) {
      if (imageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        image_ = value;
      } else {
        imageBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .components.image.v1.SDUIImageView image = 1 [json_name = "image"];</code>
     */
    public Builder setImage(
        com.cg.sdui.components.image.v1.SDUIImageView.Builder builderForValue) {
      if (imageBuilder_ == null) {
        image_ = builderForValue.build();
      } else {
        imageBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional .components.image.v1.SDUIImageView image = 1 [json_name = "image"];</code>
     */
    public Builder mergeImage(com.cg.sdui.components.image.v1.SDUIImageView value) {
      if (imageBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          image_ != null &&
          image_ != com.cg.sdui.components.image.v1.SDUIImageView.getDefaultInstance()) {
          getImageBuilder().mergeFrom(value);
        } else {
          image_ = value;
        }
      } else {
        imageBuilder_.mergeFrom(value);
      }
      if (image_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .components.image.v1.SDUIImageView image = 1 [json_name = "image"];</code>
     */
    public Builder clearImage() {
      bitField0_ = (bitField0_ & ~0x00000001);
      image_ = null;
      if (imageBuilder_ != null) {
        imageBuilder_.dispose();
        imageBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .components.image.v1.SDUIImageView image = 1 [json_name = "image"];</code>
     */
    public com.cg.sdui.components.image.v1.SDUIImageView.Builder getImageBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getImageFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .components.image.v1.SDUIImageView image = 1 [json_name = "image"];</code>
     */
    public com.cg.sdui.components.image.v1.SDUIImageViewOrBuilder getImageOrBuilder() {
      if (imageBuilder_ != null) {
        return imageBuilder_.getMessageOrBuilder();
      } else {
        return image_ == null ?
            com.cg.sdui.components.image.v1.SDUIImageView.getDefaultInstance() : image_;
      }
    }
    /**
     * <code>optional .components.image.v1.SDUIImageView image = 1 [json_name = "image"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.cg.sdui.components.image.v1.SDUIImageView, com.cg.sdui.components.image.v1.SDUIImageView.Builder, com.cg.sdui.components.image.v1.SDUIImageViewOrBuilder> 
        getImageFieldBuilder() {
      if (imageBuilder_ == null) {
        imageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.cg.sdui.components.image.v1.SDUIImageView, com.cg.sdui.components.image.v1.SDUIImageView.Builder, com.cg.sdui.components.image.v1.SDUIImageViewOrBuilder>(
                getImage(),
                getParentForChildren(),
                isClean());
        image_ = null;
      }
      return imageBuilder_;
    }

    private java.lang.Object backgroundColor_ = "";
    /**
     * <code>optional string background_color = 2 [json_name = "backgroundColor"];</code>
     * @return Whether the backgroundColor field is set.
     */
    public boolean hasBackgroundColor() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string background_color = 2 [json_name = "backgroundColor"];</code>
     * @return The backgroundColor.
     */
    public java.lang.String getBackgroundColor() {
      java.lang.Object ref = backgroundColor_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        backgroundColor_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string background_color = 2 [json_name = "backgroundColor"];</code>
     * @return The bytes for backgroundColor.
     */
    public com.google.protobuf.ByteString
        getBackgroundColorBytes() {
      java.lang.Object ref = backgroundColor_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        backgroundColor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string background_color = 2 [json_name = "backgroundColor"];</code>
     * @param value The backgroundColor to set.
     * @return This builder for chaining.
     */
    public Builder setBackgroundColor(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      backgroundColor_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional string background_color = 2 [json_name = "backgroundColor"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBackgroundColor() {
      backgroundColor_ = getDefaultInstance().getBackgroundColor();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>optional string background_color = 2 [json_name = "backgroundColor"];</code>
     * @param value The bytes for backgroundColor to set.
     * @return This builder for chaining.
     */
    public Builder setBackgroundColorBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      backgroundColor_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object header_ = "";
    /**
     * <code>optional string header = 3 [json_name = "header"];</code>
     * @return Whether the header field is set.
     */
    public boolean hasHeader() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string header = 3 [json_name = "header"];</code>
     * @return The header.
     */
    public java.lang.String getHeader() {
      java.lang.Object ref = header_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        header_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string header = 3 [json_name = "header"];</code>
     * @return The bytes for header.
     */
    public com.google.protobuf.ByteString
        getHeaderBytes() {
      java.lang.Object ref = header_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        header_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string header = 3 [json_name = "header"];</code>
     * @param value The header to set.
     * @return This builder for chaining.
     */
    public Builder setHeader(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      header_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional string header = 3 [json_name = "header"];</code>
     * @return This builder for chaining.
     */
    public Builder clearHeader() {
      header_ = getDefaultInstance().getHeader();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>optional string header = 3 [json_name = "header"];</code>
     * @param value The bytes for header to set.
     * @return This builder for chaining.
     */
    public Builder setHeaderBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      header_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object subTitle_ = "";
    /**
     * <code>optional string sub_title = 4 [json_name = "subTitle"];</code>
     * @return Whether the subTitle field is set.
     */
    public boolean hasSubTitle() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string sub_title = 4 [json_name = "subTitle"];</code>
     * @return The subTitle.
     */
    public java.lang.String getSubTitle() {
      java.lang.Object ref = subTitle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subTitle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string sub_title = 4 [json_name = "subTitle"];</code>
     * @return The bytes for subTitle.
     */
    public com.google.protobuf.ByteString
        getSubTitleBytes() {
      java.lang.Object ref = subTitle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subTitle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string sub_title = 4 [json_name = "subTitle"];</code>
     * @param value The subTitle to set.
     * @return This builder for chaining.
     */
    public Builder setSubTitle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      subTitle_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>optional string sub_title = 4 [json_name = "subTitle"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSubTitle() {
      subTitle_ = getDefaultInstance().getSubTitle();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>optional string sub_title = 4 [json_name = "subTitle"];</code>
     * @param value The bytes for subTitle to set.
     * @return This builder for chaining.
     */
    public Builder setSubTitleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      subTitle_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.cg.sdui.components.button.v1.SDUIButton button_;
    private com.google.protobuf.SingleFieldBuilder<
        com.cg.sdui.components.button.v1.SDUIButton, com.cg.sdui.components.button.v1.SDUIButton.Builder, com.cg.sdui.components.button.v1.SDUIButtonOrBuilder> buttonBuilder_;
    /**
     * <code>optional .components.button.v1.SDUIButton button = 5 [json_name = "button"];</code>
     * @return Whether the button field is set.
     */
    public boolean hasButton() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional .components.button.v1.SDUIButton button = 5 [json_name = "button"];</code>
     * @return The button.
     */
    public com.cg.sdui.components.button.v1.SDUIButton getButton() {
      if (buttonBuilder_ == null) {
        return button_ == null ? com.cg.sdui.components.button.v1.SDUIButton.getDefaultInstance() : button_;
      } else {
        return buttonBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .components.button.v1.SDUIButton button = 5 [json_name = "button"];</code>
     */
    public Builder setButton(com.cg.sdui.components.button.v1.SDUIButton value) {
      if (buttonBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        button_ = value;
      } else {
        buttonBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional .components.button.v1.SDUIButton button = 5 [json_name = "button"];</code>
     */
    public Builder setButton(
        com.cg.sdui.components.button.v1.SDUIButton.Builder builderForValue) {
      if (buttonBuilder_ == null) {
        button_ = builderForValue.build();
      } else {
        buttonBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional .components.button.v1.SDUIButton button = 5 [json_name = "button"];</code>
     */
    public Builder mergeButton(com.cg.sdui.components.button.v1.SDUIButton value) {
      if (buttonBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          button_ != null &&
          button_ != com.cg.sdui.components.button.v1.SDUIButton.getDefaultInstance()) {
          getButtonBuilder().mergeFrom(value);
        } else {
          button_ = value;
        }
      } else {
        buttonBuilder_.mergeFrom(value);
      }
      if (button_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>optional .components.button.v1.SDUIButton button = 5 [json_name = "button"];</code>
     */
    public Builder clearButton() {
      bitField0_ = (bitField0_ & ~0x00000010);
      button_ = null;
      if (buttonBuilder_ != null) {
        buttonBuilder_.dispose();
        buttonBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>optional .components.button.v1.SDUIButton button = 5 [json_name = "button"];</code>
     */
    public com.cg.sdui.components.button.v1.SDUIButton.Builder getButtonBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getButtonFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .components.button.v1.SDUIButton button = 5 [json_name = "button"];</code>
     */
    public com.cg.sdui.components.button.v1.SDUIButtonOrBuilder getButtonOrBuilder() {
      if (buttonBuilder_ != null) {
        return buttonBuilder_.getMessageOrBuilder();
      } else {
        return button_ == null ?
            com.cg.sdui.components.button.v1.SDUIButton.getDefaultInstance() : button_;
      }
    }
    /**
     * <code>optional .components.button.v1.SDUIButton button = 5 [json_name = "button"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.cg.sdui.components.button.v1.SDUIButton, com.cg.sdui.components.button.v1.SDUIButton.Builder, com.cg.sdui.components.button.v1.SDUIButtonOrBuilder> 
        getButtonFieldBuilder() {
      if (buttonBuilder_ == null) {
        buttonBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.cg.sdui.components.button.v1.SDUIButton, com.cg.sdui.components.button.v1.SDUIButton.Builder, com.cg.sdui.components.button.v1.SDUIButtonOrBuilder>(
                getButton(),
                getParentForChildren(),
                isClean());
        button_ = null;
      }
      return buttonBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:components.cards.OfferCard)
  }

  // @@protoc_insertion_point(class_scope:components.cards.OfferCard)
  private static final com.cg.sdui.components.cards.OfferCard DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cg.sdui.components.cards.OfferCard();
  }

  public static com.cg.sdui.components.cards.OfferCard getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OfferCard>
      PARSER = new com.google.protobuf.AbstractParser<OfferCard>() {
    @java.lang.Override
    public OfferCard parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<OfferCard> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OfferCard> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.cg.sdui.components.cards.OfferCard getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

