// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: components/image/v1/image.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.cg.sdui.components.image.v1;

@kotlin.jvm.JvmName("-initializesDUIImageView")
public inline fun sDUIImageView(block: com.cg.sdui.components.image.v1.SDUIImageViewKt.Dsl.() -> kotlin.Unit): com.cg.sdui.components.image.v1.SDUIImageView =
  com.cg.sdui.components.image.v1.SDUIImageViewKt.Dsl._create(com.cg.sdui.components.image.v1.SDUIImageView.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `components.image.v1.SDUIImageView`
 */
public object SDUIImageViewKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.cg.sdui.components.image.v1.SDUIImageView.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.cg.sdui.components.image.v1.SDUIImageView.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.cg.sdui.components.image.v1.SDUIImageView = _builder.build()

    /**
     * `string src = 1 [json_name = "src"];`
     */
    public var src: kotlin.String
      @kotlin.jvm.JvmName("getSrc")
        get() = _builder.src
      @kotlin.jvm.JvmName("setSrc")
        set(value) {
        _builder.src = value
      }
    /**
     * `string src = 1 [json_name = "src"];`
     */
    public fun clearSrc() {
      _builder.clearSrc()
    }

    /**
     * `string alt_text = 2 [json_name = "altText"];`
     */
    public var altText: kotlin.String
      @kotlin.jvm.JvmName("getAltText")
        get() = _builder.altText
      @kotlin.jvm.JvmName("setAltText")
        set(value) {
        _builder.altText = value
      }
    /**
     * `string alt_text = 2 [json_name = "altText"];`
     */
    public fun clearAltText() {
      _builder.clearAltText()
    }

    /**
     * `.components.image.v1.ImageStyle style = 3 [json_name = "style"];`
     */
    public var style: com.cg.sdui.components.image.v1.ImageStyle
      @kotlin.jvm.JvmName("getStyle")
        get() = _builder.style
      @kotlin.jvm.JvmName("setStyle")
        set(value) {
        _builder.style = value
      }
    /**
     * `.components.image.v1.ImageStyle style = 3 [json_name = "style"];`
     */
    public fun clearStyle() {
      _builder.clearStyle()
    }
    /**
     * `.components.image.v1.ImageStyle style = 3 [json_name = "style"];`
     * @return Whether the style field is set.
     */
    public fun hasStyle(): kotlin.Boolean {
      return _builder.hasStyle()
    }

    public val SDUIImageViewKt.Dsl.styleOrNull: com.cg.sdui.components.image.v1.ImageStyle?
      get() = _builder.styleOrNull

    /**
     * `optional .components.properties.v1.Action action = 4 [json_name = "action"];`
     */
    public var action: com.cg.sdui.components.properties.v1.Action
      @kotlin.jvm.JvmName("getAction")
        get() = _builder.action
      @kotlin.jvm.JvmName("setAction")
        set(value) {
        _builder.action = value
      }
    /**
     * `optional .components.properties.v1.Action action = 4 [json_name = "action"];`
     */
    public fun clearAction() {
      _builder.clearAction()
    }
    /**
     * `optional .components.properties.v1.Action action = 4 [json_name = "action"];`
     * @return Whether the action field is set.
     */
    public fun hasAction(): kotlin.Boolean {
      return _builder.hasAction()
    }

    public val SDUIImageViewKt.Dsl.actionOrNull: com.cg.sdui.components.properties.v1.Action?
      get() = _builder.actionOrNull
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.cg.sdui.components.image.v1.SDUIImageView.copy(block: `com.cg.sdui.components.image.v1`.SDUIImageViewKt.Dsl.() -> kotlin.Unit): com.cg.sdui.components.image.v1.SDUIImageView =
  `com.cg.sdui.components.image.v1`.SDUIImageViewKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.cg.sdui.components.image.v1.SDUIImageViewOrBuilder.styleOrNull: com.cg.sdui.components.image.v1.ImageStyle?
  get() = if (hasStyle()) getStyle() else null

public val com.cg.sdui.components.image.v1.SDUIImageViewOrBuilder.actionOrNull: com.cg.sdui.components.properties.v1.Action?
  get() = if (hasAction()) getAction() else null

